@Epic-Applicant_Information
@AuthoredBy-harshprit.kumar
@ReviewedByDEV
@AppInfoAdoption
@Perishable
            #${ApplicantType:["indiv"]}
  #FeatureID-ACAUTOCAS-159
Feature: Income Detail Non Mandatory Field Validation Without Save

  Scenario Outline: ACAUTOCAS-3881:  Validating non mandatory field <field> with <attribute> in income details without save
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "LoginDetailsCAS.xlsx" under "LoginData" and 0
    And user opens an application of "<ProductType>" product type as "<ApplicantType>" applicant at "<ApplicationStage>" for "<Category>" with "<key>" from application grid
    And user navigates to applicant details page of "<ApplicationStage>"
    And click on view edit detailed info
    And user reads data from the excel file "<PersonalInfoWB>" under sheet "<PersonalInfo_home>" and row <PersonalInfo_home_rowNum>
    And user fills home page of personal information
    And user clicks on save and next
    And user reads data from the excel file "<EmploymentDetailsWB>" under sheet "<EmploymentDetailsWB_home>" and row <EmploymentDetailsWB_home_rowNum>
    And user fills and save employment details without save and next
    And user changes major occupation to "Salaried"
    And user clicks on save and next of Employment Details
    And user reads data from the excel file "<FinancialDetailsWB>" under sheet "<FinancialDetails_incomeDetails>" and row <FinancialDetails_incomeDetails_rowNum>
    When user fills income details "<var>" more details
    Then "<field>" should be calculated "<calculation_type>"

    @Islamic
    @Release
@Part-1
    @ImplementedBy-utkarsh.tiwari
    #${ProductType:["IPF"]}
    # ${ApplicationStage:["Sourcing","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    #${Category:["bonds"]}
    Examples:
      | attribute                                                    | var     | field      | calculation_type | ProductType   | ApplicantType   | ApplicationStage   | Category   | key | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetailsWB_home | EmploymentDetailsWB_home_rowNum | FinancialDetailsWB     | FinancialDetails_incomeDetails | FinancialDetails_incomeDetails_rowNum |
      | frequency as monthly                                         | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 39                                    |
      | frequency as quarterly                                       | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 40                                    |
      | frequency as annually                                        | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 41                                    |
      | frequency as bi-monthly                                      | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 42                                    |
      | frequency as fortnighly                                      | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 43                                    |
      | frequency as half-yearly                                     | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 44                                    |
      | frequency as one time                                        | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 45                                    |
      | frequency as weekly                                          | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 46                                    |
      | change in frequency,amount,percentage and sharing_percentage | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 47                                    |
      | change in amount,percentage and sharing percentage           | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 48                                    |
      | change in percentage and sharing percentage                  | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 49                                    |
      | change in sharing percentage                                 | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 50                                    |
      | change in percentage                                         | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 51                                    |
      | change in amount                                             | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 52                                    |

    @Islamic
    @Release
@Part-1
    @ImplementedBy-utkarsh.tiwari
    #${ProductType:["IHF","IAF"]}
    # ${ApplicationStage:["Sourcing","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    Examples:
      | attribute                                                    | var     | field      | calculation_type | ProductType   | ApplicantType   | ApplicationStage   | Category | key | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetailsWB_home | EmploymentDetailsWB_home_rowNum | FinancialDetailsWB     | FinancialDetails_incomeDetails | FinancialDetails_incomeDetails_rowNum |
      | frequency as monthly                                         | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 39                                    |
      | frequency as quarterly                                       | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 40                                    |
      | frequency as annually                                        | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 41                                    |
      | frequency as bi-monthly                                      | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 42                                    |
      | frequency as fortnighly                                      | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 43                                    |
      | frequency as half-yearly                                     | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 44                                    |
      | frequency as one time                                        | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 45                                    |
      | frequency as weekly                                          | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 46                                    |
      | change in frequency,amount,percentage and sharing_percentage | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 47                                    |
      | change in amount,percentage and sharing percentage           | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 48                                    |
      | change in percentage and sharing percentage                  | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 49                                    |
      | change in sharing percentage                                 | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 50                                    |
      | change in percentage                                         | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 51                                    |
      | change in amount                                             | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 52                                    |

    @Conventional
    @Release @Part-1
    @ImplementedBy-harshprit.kumar
    #${ ProductType : ["PF","HL","MAL","EDU","OMNI","CEQ","KCC","AGRL", "FE","MHL","CV","CC","LAP"]}
   # ${ApplicationStage:["Lead Details","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    Examples:
      | attribute                                                    | var     | field      | calculation_type | ProductType   | ApplicantType   | ApplicationStage   | Category | key | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetailsWB_home | EmploymentDetailsWB_home_rowNum | FinancialDetailsWB     | FinancialDetails_incomeDetails | FinancialDetails_incomeDetails_rowNum |
      | frequency as monthly                                         | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 39                                    |
      | frequency as quarterly                                       | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 40                                    |
      | frequency as annually                                        | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 41                                    |
      | frequency as bi-monthly                                      | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 42                                    |
      | frequency as fortnighly                                      | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 43                                    |
      | frequency as half-yearly                                     | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 44                                    |
      | frequency as one time                                        | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 45                                    |
      | frequency as weekly                                          | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 46                                    |
      | change in frequency,amount,percentage and sharing_percentage | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 47                                    |
      | change in amount,percentage and sharing percentage           | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 48                                    |
      | change in percentage and sharing percentage                  | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 49                                    |
      | change in sharing percentage                                 | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 50                                    |
      | change in percentage                                         | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 51                                    |
      | change in amount                                             | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 52                                    |

     # ${ProductType:["FAS","GL","JLG","SHG"]}
    # ${ApplicationStage:["DDE","Recommendation","Credit Approval"]}
   @NotImplemented
    Examples:
      | attribute                                                    | var     | field      | calculation_type | ProductType   | ApplicantType   | ApplicationStage   | Category | key | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetailsWB_home | EmploymentDetailsWB_home_rowNum | FinancialDetailsWB     | FinancialDetails_incomeDetails | FinancialDetails_incomeDetails_rowNum |
      | frequency as monthly                                         | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 39                                    |
      | frequency as quarterly                                       | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 40                                    |
      | frequency as annually                                        | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 41                                    |
      | frequency as bi-monthly                                      | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 42                                    |
      | frequency as fortnighly                                      | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 43                                    |
      | frequency as half-yearly                                     | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 44                                    |
      | frequency as one time                                        | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 45                                    |
      | frequency as weekly                                          | without | Net Amount | automatically    | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 46                                    |
      | change in frequency,amount,percentage and sharing_percentage | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 47                                    |
      | change in amount,percentage and sharing percentage           | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 48                                    |
      | change in percentage and sharing percentage                  | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 49                                    |
      | change in sharing percentage                                 | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 50                                    |
      | change in percentage                                         | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 51                                    |
      | change in amount                                             | without | Net Amount | correctly        | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 52                                    |