@Epic-Applicant_Information
@AuthoredBy-harshprit.kumar
@ReviewedBy-harshprit.kumar
@AppInfoAdoption

#FeatureID-ACAUTOCAS-159
#${ApplicantType:["indiv"]}
Feature: Income Detail Mandatory Field Validation Before Save

  Background:
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "LoginDetailsCAS.xlsx" under "LoginData" and 0

  @FixedExp
  Scenario Outline: ACAUTOCAS-3877:  Validating <field> with <attribute> in income details without save
    And user opens an application of "<ProductType>" product type as "<ApplicantType>" applicant at "<ApplicationStage>" for "<Category>" with "<key>" from application grid
    And user navigates to applicant details page of "<ApplicationStage>"
    And click on view edit detailed info
    And user reads data from the excel file "<EmploymentDetailsWB>" under sheet "<EmploymentDetailsWB_home>" and row <EmploymentDetailsWB_home_rowNum>
    And user open Employment Details
    And user add Single "<OccupationType>" Occupation in Employment Details
    And user changes major occupation to "<OccupationType>"
    And user clicks on save and next of Employment Details
    And user open financial details
    And user reads data from the excel file "<FinancialDetailsWB>" under sheet "<FinancialDetails_incomeDetails>" and row <FinancialDetails_incomeDetails_rowNum>
    When user fills income details "<var>" more details
    Then "<validity>" message should display around "<field>" field
    @Conventional
    @Release @Part-1
    @ImplementedBy-harshprit.kumar
    #${ ProductType : ["PF","HL","MAL","EDU","OMNI","CEQ","KCC","AGRL", "FE","MHL","CV","CC","LAP"]}
    # ${ApplicationStage:["Lead Details","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | OccupationType | attribute                  | var     | field      | validity | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetailsWB_home | EmploymentDetailsWB_home_rowNum | FinancialDetailsWB     | FinancialDetails_incomeDetails | FinancialDetails_incomeDetails_rowNum |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | null                       | without | Frequency  | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 6                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | maximum length             | without | Amount     | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 7                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | both digits and characters | without | Amount     | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 8                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | negative value             | without | Amount     | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 9                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | special character          | without | Amount     | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 10                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | space                      | without | Amount     | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 11                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | more than 100              | without | Percentage | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 12                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | both digits and characters | without | Percentage | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 13                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | negative value             | without | Percentage | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 14                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | special characters         | without | Percentage | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 15                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | space                      | without | Percentage | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 16                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | more than 100              | without | Sharing    | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 17                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | both digits and characters | without | Sharing    | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 18                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | negative value             | without | Sharing    | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 19                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | special characters         | without | Sharing    | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 20                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | space                      | without | Sharing    | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 21                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | valid value                | without | Amount     | no error | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 23                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | maximum value              | without | Amount     | no error | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 24                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | decimal format             | without | Amount     | no error | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 25                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | valid value                | without | Percentage | no error | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 23                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | decimal format             | without | Percentage | no error | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 26                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | valid value                | without | Sharing    | no error | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 23                                    |
    @Islamic
    @Release
    @Part-1
    @ImplementedBy-akash.bansal
    #${ProductType:["IHF","IAF"]}
    # ${ApplicationStage:["Sourcing","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | OccupationType | attribute                  | var     | field      | validity | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetailsWB_home | EmploymentDetailsWB_home_rowNum | FinancialDetailsWB     | FinancialDetails_incomeDetails | FinancialDetails_incomeDetails_rowNum |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | null                       | without | Frequency  | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 6                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | maximum length             | without | Amount     | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 7                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | both digits and characters | without | Amount     | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 8                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | negative value             | without | Amount     | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 9                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | special character          | without | Amount     | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 10                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | space                      | without | Amount     | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 11                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | more than 100              | without | Percentage | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 12                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | both digits and characters | without | Percentage | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 13                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | negative value             | without | Percentage | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 14                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | special characters         | without | Percentage | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 15                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | space                      | without | Percentage | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 16                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | more than 100              | without | Sharing    | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 17                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | both digits and characters | without | Sharing    | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 18                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | negative value             | without | Sharing    | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 19                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | special characters         | without | Sharing    | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 20                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | space                      | without | Sharing    | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 21                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | valid value                | without | Amount     | no error | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 23                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | maximum value              | without | Amount     | no error | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 24                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | decimal format             | without | Amount     | no error | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 25                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | valid value                | without | Percentage | no error | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 23                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | decimal format             | without | Percentage | no error | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 26                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | valid value                | without | Sharing    | no error | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 23                                    |
    @Islamic
    @Release
    @Part-1
    @ImplementedBy-akash.bansal
    #${ProductType:["IPF"]}
    # ${ApplicationStage:["Sourcing","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    #${Category:["bonds"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category   | key | OccupationType | attribute                  | var     | field      | validity | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetailsWB_home | EmploymentDetailsWB_home_rowNum | FinancialDetailsWB     | FinancialDetails_incomeDetails | FinancialDetails_incomeDetails_rowNum |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | null                       | without | Frequency  | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 6                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | maximum length             | without | Amount     | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 7                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | both digits and characters | without | Amount     | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 8                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | negative value             | without | Amount     | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 9                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | special character          | without | Amount     | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 10                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | space                      | without | Amount     | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 11                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | more than 100              | without | Percentage | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 12                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | both digits and characters | without | Percentage | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 13                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | negative value             | without | Percentage | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 14                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | special characters         | without | Percentage | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 15                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | space                      | without | Percentage | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 16                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | more than 100              | without | Sharing    | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 17                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | both digits and characters | without | Sharing    | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 18                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | negative value             | without | Sharing    | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 19                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | special characters         | without | Sharing    | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 20                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | space                      | without | Sharing    | error    | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 21                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | valid value                | without | Amount     | no error | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 23                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | maximum value              | without | Amount     | no error | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 24                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | decimal format             | without | Amount     | no error | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 25                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | valid value                | without | Percentage | no error | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 23                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | decimal format             | without | Percentage | no error | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 26                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | valid value                | without | Sharing    | no error | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 23                                    |
     # ${ProductType:["FAS","GL","JLG","SHG"]}
    # ${ApplicationStage:["DDE","Recommendation","Credit Approval"]}
    @NotImplemented
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | OccupationType | attribute                  | var     | field      | validity | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetailsWB_home | EmploymentDetailsWB_home_rowNum | FinancialDetailsWB     | FinancialDetails_incomeDetails | FinancialDetails_incomeDetails_rowNum |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | null                       | without | Frequency  | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 6                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | maximum length             | without | Amount     | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 7                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | both digits and characters | without | Amount     | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 8                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | negative value             | without | Amount     | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 9                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | special character          | without | Amount     | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 10                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | space                      | without | Amount     | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 11                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | more than 100              | without | Percentage | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 12                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | both digits and characters | without | Percentage | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 13                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | negative value             | without | Percentage | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 14                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | special characters         | without | Percentage | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 15                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | space                      | without | Percentage | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 16                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | more than 100              | without | Sharing    | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 17                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | both digits and characters | without | Sharing    | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 18                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | negative value             | without | Sharing    | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 19                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | special characters         | without | Sharing    | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 20                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | space                      | without | Sharing    | error    | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 21                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | valid value                | without | Amount     | no error | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 23                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | maximum value              | without | Amount     | no error | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 24                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | decimal format             | without | Amount     | no error | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 25                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | valid value                | without | Percentage | no error | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 23                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | decimal format             | without | Percentage | no error | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 26                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | valid value                | without | Sharing    | no error | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 23                                    |

  @FixedExp
  Scenario Outline: ACAUTOCAS-3878:  <field> should be <attribute> in income details without save
    And user opens an application of "<ProductType>" product type as "<ApplicantType>" applicant at "<ApplicationStage>" for "<Category>" with "<key>" from application grid
    And user navigates to applicant details page of "<ApplicationStage>"
    And click on view edit detailed info
    And user reads data from the excel file "<EmploymentDetailsWB>" under sheet "<EmploymentDetailsWB_home>" and row <EmploymentDetailsWB_home_rowNum>
    And user open Employment Details
    And user add Single "<OccupationType>" Occupation in Employment Details
    And user changes major occupation to "<OccupationType>"
    And user clicks on save and next of Employment Details
    And user open financial details
    And user reads data from the excel file "<FinancialDetailsWB>" under sheet "<FinancialDetails_incomeDetails>" and row <FinancialDetails_incomeDetails_rowNum>
    When user fills income details "<var>" more details
    Then functionality of "<attribute>" should work work successfully around "<field>"
    @Conventional
    @Release @Part-1
    @ImplementedBy-harshprit.kumar
    #${ ProductType : ["PF","HL","MAL","EDU","OMNI","CEQ","KCC","AGRL", "FE","MHL","CV","CC","LAP"]}
    # ${ApplicationStage:["Lead Details","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | OccupationType | attribute       | var     | field      | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetailsWB_home | EmploymentDetailsWB_home_rowNum | FinancialDetailsWB     | FinancialDetails_incomeDetails | FinancialDetails_incomeDetails_rowNum |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | change in value | without | Currency   | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 0                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | not editable    | without | Net Amount | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 0                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | correct         | without | Net Amount | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 0                                     |
    @Islamic
    @Release
    @Part-1
    @ImplementedBy-akash.bansal
    #${ProductType:["IHF","IAF"]}
    # ${ApplicationStage:["Sourcing","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | OccupationType | attribute       | var     | field      | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetailsWB_home | EmploymentDetailsWB_home_rowNum | FinancialDetailsWB     | FinancialDetails_incomeDetails | FinancialDetails_incomeDetails_rowNum |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | change in value | without | Currency   | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 0                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | not editable    | without | Net Amount | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 0                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | correct         | without | Net Amount | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 0                                     |
    @Islamic
    @Release
    @Part-1
    @ImplementedBy-akash.bansal
    #${ProductType:["IPF"]}
    # ${ApplicationStage:["Sourcing","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    #${Category:["bonds"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category   | key | OccupationType | attribute       | var     | field      | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetailsWB_home | EmploymentDetailsWB_home_rowNum | FinancialDetailsWB     | FinancialDetails_incomeDetails | FinancialDetails_incomeDetails_rowNum |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | change in value | without | Currency   | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 0                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | not editable    | without | Net Amount | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 0                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | Salaried       | correct         | without | Net Amount | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                     | 136                             | financial_details.xlsx | income_details                 | 0                                     |
     # ${ProductType:["FAS","GL","JLG","SHG"]}
    # ${ApplicationStage:["DDE","Recommendation","Credit Approval"]}
    @NotImplemented
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | OccupationType | attribute       | var     | field      | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetailsWB_home | EmploymentDetailsWB_home_rowNum | FinancialDetailsWB     | FinancialDetails_incomeDetails | FinancialDetails_incomeDetails_rowNum |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | change in value | without | Currency   | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 0                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | not editable    | without | Net Amount | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 0                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | Salaried       | correct         | without | Net Amount | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                     | 8                               | financial_details.xlsx | income_details                 | 0                                     |
