@Epic-Applicant_Information
@AuthoredBy-vipin.kishor
@ReviewedBy-None
@Reconciled
@ReviewedByDEV
@AppInfoAdoption
@Experiment
#FeatureID-ACAUTOCAS-158

# ${ApplicantType:["indiv"]}
Feature: Field validation with Self Employed Professional in Employment Detail


  Scenario Outline: ACAUTOCAS-3843:  Entering <Validity> <Field_Name> <Validity_Reason> in Self Employed Professional
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "LoginDetailsCAS.xlsx" under "LoginData" and 0
    And user opens an application of "<ProductType>" product type as "<ApplicantType>" applicant at "<ApplicationStage>" for "<Category>" with "<key>" from application grid
    And user navigates to applicant details page of "<ApplicationStage>"
    And click on view edit detailed info
    And user reads data from the excel file "<EmploymentDetailsWB>" under sheet "<EmploymentDetails_home>" and row <EmploymentDetails_home_rowNum>
    And user open Employment Details
    When user enters "<Validity>" "<Field_Name>" "<Validity_Reason>" for self employed professional in Employment Details
    Then application "<Throws_notThrows>" "<With_Error_Message>"
    @Conventional
    @Release @Part-1
    @ImplementedBy-aman.nagarkoti
    #${ ProductType : ["PF","HL","MAL","EDU","OMNI","CEQ","KCC","AGRL", "FE","MHL","CV","CC","LAP"]}
    # ${ApplicationStage:["Lead Details","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | Validity | Field_Name                | Validity_Reason                           | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | Throws_notThrows                   | With_Error_Message                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | organisation_name         | with_max_characters                       | employment_details.xlsx | home                   | 39                            | does_not_throw_any_error           |                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | organisation_name         | with_only_characters                      | employment_details.xlsx | home                   | 40                            | does_not_throw_any_error           |                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | organisation_name         | with_digits                               | employment_details.xlsx | home                   | 41                            | does_not_throw_any_error           |                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | organisation_name         | with_special_characters ' , / - & ( ) !.$ | employment_details.xlsx | home                   | 42                            | does_not_throw_any_error           |                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | organisation_name         | with_special_characters @ #               | employment_details.xlsx | home                   | 43                            | throws an error with error message | Please input valid characters.                        |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | organisation_name         | with_spaces                               | employment_details.xlsx | home                   | 44                            | does_not_throw_any_error           |                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | years_in_work_experience  |                                           | employment_details.xlsx | home                   | 45                            | does_not_throw_any_error           |                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | years_in_work_experience  | with_characters                           | employment_details.xlsx | home                   | 46                            | throws an error with error message | Please enter only digits                              |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | years_in_work_experience  | with_special_characters                   | employment_details.xlsx | home                   | 47                            | throws an error with error message | Please enter only digits                              |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | months_in_work_experience |                                           | employment_details.xlsx | home                   | 48                            | does_not_throw_any_error           |                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | months_in_work_experience | with_characters                           | employment_details.xlsx | home                   | 49                            | throws an error with error message | Please enter only digits                              |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | months_in_work_experience | with_special_characters                   | employment_details.xlsx | home                   | 50                            | throws an error with error message | Please enter only digits                              |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | end_date                  | with_date_less_than_start_date            | employment_details.xlsx | home                   | 51                            | throws an error with error message | End date must be greater than or equal to Start date. |
    @Islamic
    @Release
@Part-1
    @ImplementedBy-akash.bansal
    #${ProductType:["IHF","IAF"]}
    # ${ApplicationStage:["Sourcing","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | Validity | Field_Name                | Validity_Reason                           | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | Throws_notThrows                   | With_Error_Message                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | organisation_name         | with_max_characters                       | employment_details.xlsx | home                   | 39                            | does_not_throw_any_error           |                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | organisation_name         | with_only_characters                      | employment_details.xlsx | home                   | 40                            | does_not_throw_any_error           |                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | organisation_name         | with_digits                               | employment_details.xlsx | home                   | 41                            | does_not_throw_any_error           |                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | organisation_name         | with_special_characters ' , / - & ( ) !.$ | employment_details.xlsx | home                   | 42                            | does_not_throw_any_error           |                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | organisation_name         | with_special_characters @ #               | employment_details.xlsx | home                   | 43                            | throws an error with error message | Please input valid characters.                        |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | organisation_name         | with_spaces                               | employment_details.xlsx | home                   | 44                            | does_not_throw_any_error           |                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | years_in_work_experience  |                                           | employment_details.xlsx | home                   | 45                            | does_not_throw_any_error           |                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | years_in_work_experience  | with_characters                           | employment_details.xlsx | home                   | 46                            | throws an error with error message | Please enter only Digits.                             |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | years_in_work_experience  | with_special_characters                   | employment_details.xlsx | home                   | 47                            | throws an error with error message | Please enter only Digits.                             |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | months_in_work_experience |                                           | employment_details.xlsx | home                   | 48                            | does_not_throw_any_error           |                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | months_in_work_experience | with_characters                           | employment_details.xlsx | home                   | 49                            | throws an error with error message | Please enter only Digits.                             |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | months_in_work_experience | with_special_characters                   | employment_details.xlsx | home                   | 50                            | throws an error with error message | Please enter only Digits.                             |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | end_date                  | with_date_less_than_start_date            | employment_details.xlsx | home                   | 51                            | throws an error with error message | End date must be greater than or equal to Start date. |
    @Islamic
    @Release
@Part-1
    @ImplementedBy-akash.bansal
    #${ProductType:["IPF"]}
    # ${ApplicationStage:["Sourcing","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    #${Category:["bonds"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category   | key | Validity | Field_Name                | Validity_Reason                           | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | Throws_notThrows                   | With_Error_Message                                    |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | organisation_name         | with_max_characters                       | employment_details.xlsx | home                   | 39                            | does_not_throw_any_error           |                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | organisation_name         | with_only_characters                      | employment_details.xlsx | home                   | 40                            | does_not_throw_any_error           |                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | organisation_name         | with_digits                               | employment_details.xlsx | home                   | 41                            | does_not_throw_any_error           |                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | organisation_name         | with_special_characters ' , / - & ( ) !.$ | employment_details.xlsx | home                   | 42                            | does_not_throw_any_error           |                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | organisation_name         | with_special_characters @ #               | employment_details.xlsx | home                   | 43                            | throws an error with error message | Please input valid characters.                        |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | organisation_name         | with_spaces                               | employment_details.xlsx | home                   | 44                            | does_not_throw_any_error           |                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | years_in_work_experience  |                                           | employment_details.xlsx | home                   | 45                            | does_not_throw_any_error           |                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | years_in_work_experience  | with_characters                           | employment_details.xlsx | home                   | 46                            | throws an error with error message | Please enter only Digits.                             |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | years_in_work_experience  | with_special_characters                   | employment_details.xlsx | home                   | 47                            | throws an error with error message | Please enter only Digits.                             |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | months_in_work_experience |                                           | employment_details.xlsx | home                   | 48                            | does_not_throw_any_error           |                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | months_in_work_experience | with_characters                           | employment_details.xlsx | home                   | 49                            | throws an error with error message | Please enter only Digits.                             |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | months_in_work_experience | with_special_characters                   | employment_details.xlsx | home                   | 50                            | throws an error with error message | Please enter only Digits.                             |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | end_date                  | with_date_less_than_start_date            | employment_details.xlsx | home                   | 51                            | throws an error with error message | End date must be greater than or equal to Start date. |
    @NotImplemented
       # ${ProductType:["FAS","GL","JLG","SHG"]}
    # ${ApplicationStage:["DDE","Recommendation","Credit Approval"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | Validity | Field_Name                | Validity_Reason                           | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | Throws_notThrows                   | With_Error_Message                                               |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | organisation_name         | with_max_characters                       | employment_details.xlsx | home                   | 39                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | organisation_name         | with_only_characters                      | employment_details.xlsx | home                   | 40                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | organisation_name         | with_digits                               | employment_details.xlsx | home                   | 41                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | organisation_name         | with_special_characters ' , / - & ( ) !.$ | employment_details.xlsx | home                   | 42                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | organisation_name         | with_special_characters @ #               | employment_details.xlsx | home                   | 43                            | throws an error with error message | Only Alphabets,Numbers and ' , / - & ( ) !.$ spaces are allowed. |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | organisation_name         | with_spaces                               | employment_details.xlsx | home                   | 44                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | years_in_work_experience  |                                           | employment_details.xlsx | home                   | 45                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | years_in_work_experience  | with_characters                           | employment_details.xlsx | home                   | 46                            | throws an error with error message | Please enter only Digits.                                        |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | years_in_work_experience  | with_special_characters                   | employment_details.xlsx | home                   | 47                            | throws an error with error message | Please enter only Digits.                                        |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | months_in_work_experience |                                           | employment_details.xlsx | home                   | 48                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | months_in_work_experience | with_characters                           | employment_details.xlsx | home                   | 49                            | throws an error with error message | Please enter only Digits.                                        |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | months_in_work_experience | with_special_characters                   | employment_details.xlsx | home                   | 50                            | throws an error with error message | Please enter only Digits.                                        |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | end_date                  | with_date_less_than_start_date            | employment_details.xlsx | home                   | 51                            | throws an error with error message | End date must be greater than or equal to Start date.            |
