@Epic-Applicant_Information
@AuthoredBy-vipin.kishor
@ReviewedBy-None
@ReviewedByDEV
@AppInfoAdoption
@Experiment
# ${ApplicantType:["indiv"]}
  #FeatureID-ACAUTOCAS-158
Feature: Field validation with Salaried Occupation in Employment Detail

  Scenario Outline: ACAUTOCAS-3830:  Entering <Validity> <Field_Name> <Validity_Reason> in Salaried Occupation
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and <RowNumber>
    And user opens an application of "<ProductType>" product type as "<ApplicantType>" applicant at "<ApplicationStage>" for "<Category>" with "<key>" from application grid
    And user navigates to applicant details page of "<ApplicationStage>"
    When click on view edit detailed info
    And user reads data from the excel file "<EmploymentDetailsWB>" under sheet "<EmploymentDetails_home>" and row <EmploymentDetails_home_rowNum>
    And user open Employment Details
    And user enters "<Validity>" "<Field_Name>" "<Validity_Reason>" in Employment Details
    Then application "<Throws_notThrows>" "<With_Error_Message>" in salaried occupation
    @Conventional
    @Release @Part-1
    @ImplementedBy-aman.nagarkoti
    #${ ProductType : ["PF","HL","MAL","EDU","OMNI","CEQ","KCC","AGRL", "FE","MHL","CV","CC","LAP"]}
    # ${ApplicationStage:["Lead Details","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | Validity | Field_Name         | Validity_Reason                       | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | Throws_notThrows                   | With_Error_Message                                               |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | company_website    | with_max_characters                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 12                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | company_website    |                                       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 13                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | company_website    | with_characters                       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 14                            | throws an error with error message | Not a valid URL. It should be like www.nucleussoftware.com       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | company_website    | with_digits                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 15                            | throws an error with error message | Not a valid URL. It should be like www.nucleussoftware.com       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | company_website    | with_special_characters               | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 16                            | throws an error with error message | Not a valid URL. It should be like www.nucleussoftware.com       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | company_website    | with_spaces                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 17                            | throws an error with error message | Not a valid URL. It should be like www.nucleussoftware.com       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | department_name    | with_max_characters                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 19                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | department_name    | with_characters                       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 20                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | department_name    | with_digits                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 21                            | throws an error with error message | Only alphabets allowed.                                          |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | department_name    | with_special_characters               | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 22                            | throws an error with error message | Only alphabets allowed.                                          |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | department_name    | with_spaces                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 23                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | designation        | with_max_characters                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 24                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | designation        | with_characters                       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 25                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | designation        | with_characters_starting_with_numbers | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 26                            | throws an error with error message | Please enter a valid designation, starting with alphabets.       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | designation        | with_characters_ending_with_numbers   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 27                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | designation        | with_digits                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 28                            | throws an error with error message | Please enter a valid designation, starting with alphabets.       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | designation        | with_special_characters               | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 29                            | throws an error with error message | Please enter a valid designation, starting with alphabets.       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | designation        | with_spaces                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 30                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | employed_till_date | with_date_less_than_employed_from     | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 31                            | throws an error with error message | Employment till date should be greater than employment from date |
    @Islamic
    @Release
@Part-1
    @ImplementedBy-akash.bansal
    #${ProductType:["IHF","IAF"]}
    # ${ApplicationStage:["Sourcing","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | Validity | Field_Name         | Validity_Reason                       | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | Throws_notThrows                   | With_Error_Message                                               |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | company_website    | with_max_characters                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 12                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | company_website    |                                       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 13                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | company_website    | with_characters                       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 14                            | throws an error with error message | Not a valid URL. It should be like www.nucleussoftware.com       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | company_website    | with_digits                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 15                            | throws an error with error message | Not a valid URL. It should be like www.nucleussoftware.com       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | company_website    | with_special_characters               | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 16                            | throws an error with error message | Not a valid URL. It should be like www.nucleussoftware.com       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | company_website    | with_spaces                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 17                            | throws an error with error message | Not a valid URL. It should be like www.nucleussoftware.com       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | department_name    | with_max_characters                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 19                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | department_name    | with_characters                       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 20                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | department_name    | with_digits                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 21                            | throws an error with error message | Only alphabets allowed.                                          |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | department_name    | with_special_characters               | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 22                            | throws an error with error message | Only alphabets allowed.                                          |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | department_name    | with_spaces                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 23                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | designation        | with_max_characters                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 24                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | designation        | with_characters                       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 25                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | designation        | with_characters_starting_with_numbers | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 26                            | throws an error with error message | Please enter a valid designation, starting with alphabets.       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | designation        | with_characters_ending_with_numbers   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 27                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | designation        | with_digits                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 28                            | throws an error with error message | Please enter a valid designation, starting with alphabets.       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | designation        | with_special_characters               | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 29                            | throws an error with error message | Please enter a valid designation, starting with alphabets.       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | designation        | with_spaces                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 30                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | employed_till_date | with_date_less_than_employed_from     | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 31                            | throws an error with error message | Employment till date should be greater than employment from date |
    @Islamic
    @Release
@Part-1
    @ImplementedBy-akash.bansal
    #${ProductType:["IPF"]}
    # ${ApplicationStage:["Sourcing","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    #${Category:["bonds"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category   | key | Validity | Field_Name         | Validity_Reason                       | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | Throws_notThrows                   | With_Error_Message                                               |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | company_website    | with_max_characters                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 12                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | company_website    |                                       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 13                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | company_website    | with_characters                       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 14                            | throws an error with error message | Not a valid URL. It should be like www.nucleussoftware.com       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | company_website    | with_digits                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 15                            | throws an error with error message | Not a valid URL. It should be like www.nucleussoftware.com       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | company_website    | with_special_characters               | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 16                            | throws an error with error message | Not a valid URL. It should be like www.nucleussoftware.com       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | company_website    | with_spaces                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 17                            | throws an error with error message | Not a valid URL. It should be like www.nucleussoftware.com       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | department_name    | with_max_characters                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 19                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | department_name    | with_characters                       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 20                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | department_name    | with_digits                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 21                            | throws an error with error message | Only alphabets allowed.                                          |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | department_name    | with_special_characters               | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 22                            | throws an error with error message | Only alphabets allowed.                                          |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | department_name    | with_spaces                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 23                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | designation        | with_max_characters                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 24                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | designation        | with_characters                       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 25                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | designation        | with_characters_starting_with_numbers | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 26                            | throws an error with error message | Please enter a valid designation, starting with alphabets.       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | designation        | with_characters_ending_with_numbers   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 27                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | designation        | with_digits                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 28                            | throws an error with error message | Please enter a valid designation, starting with alphabets.       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | designation        | with_special_characters               | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 29                            | throws an error with error message | Please enter a valid designation, starting with alphabets.       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | designation        | with_spaces                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 30                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | employed_till_date | with_date_less_than_employed_from     | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 31                            | throws an error with error message | Employment till date should be greater than employment from date |
    @NotImplemented
       # ${ProductType:["FAS","GL","JLG","SHG"]}
    # ${ApplicationStage:["DDE","Recommendation","Credit Approval"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | Validity | Field_Name         | Validity_Reason                       | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | Throws_notThrows                   | With_Error_Message                                               |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | company_website    | with_max_characters                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 12                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | company_website    |                                       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 13                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | company_website    | with_characters                       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 14                            | throws an error with error message | Not a valid URL. It should be like www.nucleussoftware.com       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | company_website    | with_digits                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 15                            | throws an error with error message | Not a valid URL. It should be like www.nucleussoftware.com       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | company_website    | with_special_characters               | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 16                            | throws an error with error message | Not a valid URL. It should be like www.nucleussoftware.com       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | company_website    | with_spaces                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 17                            | throws an error with error message | Not a valid URL. It should be like www.nucleussoftware.com       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | department_name    | with_max_characters                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 19                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | department_name    | with_characters                       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 20                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | department_name    | with_digits                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 21                            | throws an error with error message | Only alphabets allowed.                                          |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | department_name    | with_special_characters               | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 22                            | throws an error with error message | Only alphabets allowed.                                          |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | department_name    | with_spaces                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 23                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | designation        | with_max_characters                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 24                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | designation        | with_characters                       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 25                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | designation        | with_characters_starting_with_numbers | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 26                            | throws an error with error message | Please enter a valid designation, starting with alphabets.       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | designation        | with_characters_ending_with_numbers   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 27                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | designation        | with_digits                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 28                            | throws an error with error message | Please enter a valid designation, starting with alphabets.       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | designation        | with_special_characters               | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 29                            | throws an error with error message | Please enter a valid designation, starting with alphabets.       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | designation        | with_spaces                           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 30                            | does_not_throw_any_error           |                                                                  |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | employed_till_date | with_date_less_than_employed_from     | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 31                            | throws an error with error message | Employment till date should be greater than employment from date |
