@Epic-Loan_Application_Details
@AuthoredBy-harshita.nayak
@ReviewedBy-None
@ImplementedBy-utkarsh.tiwari
@Release1
@Conventional

Feature: CERSAI Details Mandatory Field Validation Before Save

  Scenario Outline: ACAUTOCAS-4048: Validating serial number field in CERSAI Details with <var>
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and <RowNumber>
    And user create new application for "<Loan_Type>"
    And user reads data from the excel file "<SourcingDetailsWB>" under sheet "<SourcingDetails_home>" and row <SourcingDetails_home_rowNum>
    And user fills and saves sourcing details
    And user reads data from the excel file "<PropertyDetailsWB>" under sheet "<PropertyDetails_home>" and row <PropertyDetails_home_rowNum>
    And user fills property details home page with "<Mandatory_NonMandatory>" fields for "<Application_Type>"
    And user reads data from the excel file "<PropertyDetailsWB>" under sheet "<PropertyDetails_otherDetails>" and row <PropertyDetails_otherDetails_rowNum>
    And user fills other details of property details with "<Mandatory_NonMandatory>" fields for "<Application_Type>"
    And user reads data from the excel file "<PropertyDetailsWB>" under sheet "<PropertyDetails_propertyAddress>" and row <PropertyDetails_propertyAddress_rowNum>
    And user fills property address with "<Mandatory_NonMandatory>" fields for "<Application_Type>"
    And user saves property details
    And user reads data from the excel file "<PropertyDetailsWB>" under sheet "<PropertyDetails_cersai>" and row <PropertyDetails_cersai_rowNum>
    When user fills serial number with "<var>" in CERSAI details
    Then serial number "<Throws_notThrows>" "<With_Error_Message>"

    Examples:
      | Loan_Type | var                        | Mandatory_NonMandatory | Throws_notThrows                   | With_Error_Message                | Application_Type    | Loan_Type | SourceDataFile       | SheetName | RowNumber | SourcingDetailsWB     | SourcingDetails_home | SourcingDetails_home_rowNum |  | PropertyDetailsWB     | PropertyDetails_home | PropertyDetails_home_rowNum | PropertyDetails_otherDetails | PropertyDetails_otherDetails_rowNum | PropertyDetails_propertyAddress | PropertyDetails_propertyAddress_rowNum | PropertyDetails_cersai | PropertyDetails_cersai_rowNum |
      | Home Loan | valid value                | mandatory              | does not throw any error           |                                   | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 0                             |
      | Home Loan | maximum length             | mandatory              | throws an error with error message | Number should have only 3 digits. | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 1                             |
      | Home Loan | both digits and characters | mandatory              | throws an error with error message | Please enter only Digits.         | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 2                             |
      | Home Loan | special characters         | mandatory              | throws an error with error message | Please enter only Digits.         | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 3                             |
      | Home Loan | space                      | mandatory              | throws an error with error message | Please enter only Digits.         | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 4                             |
      | Home Loan | negative value             | mandatory              | throws an error with error message | Please enter only Digits.         | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 5                             |


  Scenario Outline: ACAUTOCAS-4049: Validating Number of Documents field in CERSAI Details with <var>
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and <RowNumber>
    And user create new application for "<Loan_Type>"
    And user reads data from the excel file "<SourcingDetailsWB>" under sheet "<SourcingDetails_home>" and row <SourcingDetails_home_rowNum>
    And user fills and saves sourcing details
    And user reads data from the excel file "<PropertyDetailsWB>" under sheet "<PropertyDetails_home>" and row <PropertyDetails_home_rowNum>
    And user fills property details home page with "<Mandatory_NonMandatory>" fields for "<Application_Type>"
    And user reads data from the excel file "<PropertyDetailsWB>" under sheet "<PropertyDetails_otherDetails>" and row <PropertyDetails_otherDetails_rowNum>
    And user fills other details of property details with "<Mandatory_NonMandatory>" fields for "<Application_Type>"
    And user reads data from the excel file "<PropertyDetailsWB>" under sheet "<PropertyDetails_propertyAddress>" and row <PropertyDetails_propertyAddress_rowNum>
    And user fills property address with "<Mandatory_NonMandatory>" fields for "<Application_Type>"
    And user saves property details
    And user reads data from the excel file "<PropertyDetailsWB>" under sheet "<PropertyDetails_cersai>" and row <PropertyDetails_cersai_rowNum>
    When user fills Number of Documents with "<var>" in CERSAI details
    Then Number of Documents "<Throws_notThrows>" "<With_Error_Message>"

    Examples:
      | Loan_Type | var                        | Mandatory_NonMandatory | Throws_notThrows                   | With_Error_Message                | Application_Type    | Loan_Type | SourceDataFile       | SheetName | RowNumber | SourcingDetailsWB     | SourcingDetails_home | SourcingDetails_home_rowNum |  | PropertyDetailsWB     | PropertyDetails_home | PropertyDetails_home_rowNum | PropertyDetails_otherDetails | PropertyDetails_otherDetails_rowNum | PropertyDetails_propertyAddress | PropertyDetails_propertyAddress_rowNum | PropertyDetails_cersai | PropertyDetails_cersai_rowNum |
      | Home Loan | valid value                | mandatory              | does not throw any error           |                                   | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 0                             |
      | Home Loan | maximum length             | mandatory              | throws an error with error message | Number should have only 3 digits. | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 1                             |
      | Home Loan | both digits and characters | mandatory              | throws an error with error message | Please enter only Digits.         | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 2                             |
      | Home Loan | special characters         | mandatory              | throws an error with error message | Please enter only Digits.         | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 3                             |
      | Home Loan | space                      | mandatory              | throws an error with error message | Please enter only Digits.         | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 4                             |
      | Home Loan | negative value             | mandatory              | throws an error with error message | Please enter only Digits.         | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 5                             |

  Scenario Outline: ACAUTOCAS-4050: Validating Title Document Number field in CERSAI Details with <var>
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and <RowNumber>
    And user create new application for "<Loan_Type>"
    And user reads data from the excel file "<SourcingDetailsWB>" under sheet "<SourcingDetails_home>" and row <SourcingDetails_home_rowNum>
    And user fills and saves sourcing details
    And user reads data from the excel file "<PropertyDetailsWB>" under sheet "<PropertyDetails_home>" and row <PropertyDetails_home_rowNum>
    And user fills property details home page with "<Mandatory_NonMandatory>" fields for "<Application_Type>"
    And user reads data from the excel file "<PropertyDetailsWB>" under sheet "<PropertyDetails_otherDetails>" and row <PropertyDetails_otherDetails_rowNum>
    And user fills other details of property details with "<Mandatory_NonMandatory>" fields for "<Application_Type>"
    And user reads data from the excel file "<PropertyDetailsWB>" under sheet "<PropertyDetails_propertyAddress>" and row <PropertyDetails_propertyAddress_rowNum>
    And user fills property address with "<Mandatory_NonMandatory>" fields for "<Application_Type>"
    And user saves property details
    And user reads data from the excel file "<PropertyDetailsWB>" under sheet "<PropertyDetails_cersai>" and row <PropertyDetails_cersai_rowNum>
    When user fills Title Document Number with "<var>" in CERSAI details
    Then Title Document Number "<Throws_notThrows>" "<With_Error_Message>"

    Examples:
      | Loan_Type | var                            | Mandatory_NonMandatory | Throws_notThrows                   | With_Error_Message                | Application_Type    | Loan_Type | SourceDataFile       | SheetName | RowNumber | SourcingDetailsWB     | SourcingDetails_home | SourcingDetails_home_rowNum |  | PropertyDetailsWB     | PropertyDetails_home | PropertyDetails_home_rowNum | PropertyDetails_otherDetails | PropertyDetails_otherDetails_rowNum | PropertyDetails_propertyAddress | PropertyDetails_propertyAddress_rowNum | PropertyDetails_cersai | PropertyDetails_cersai_rowNum |
      | Home Loan | valid value                    | mandatory              | does not throw any error           |                                   | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 0                             |
      | Home Loan | maximum length                 | mandatory              | does not throw any error           | Number should have only 3 digits. | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 1                             |
      | Home Loan | both digits and characters     | mandatory              | does not throw any error           | Please enter only Digits.         | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 2                             |
      | Home Loan | special characters             | mandatory              | throws an error with error message | Please enter only Digits.         | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 3                             |
      | Home Loan | space                          | mandatory              | does not throw any error           | Please enter only Digits.         | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 4                             |
      | Home Loan | negative value                 | mandatory              | does not throw any error           | Please enter only Digits.         | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 5                             |
      | Home Loan | special characters with hyphen | mandatory              | does not throw any error           | Please enter only Digits.         | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 5                             |


  Scenario Outline: ACAUTOCAS-4051: Validating Sub Registrar Office field in CERSAI Details with <var>
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and <RowNumber>
    And user create new application for "<Loan_Type>"
    And user reads data from the excel file "<SourcingDetailsWB>" under sheet "<SourcingDetails_home>" and row <SourcingDetails_home_rowNum>
    And user fills and saves sourcing details
    And user reads data from the excel file "<PropertyDetailsWB>" under sheet "<PropertyDetails_home>" and row <PropertyDetails_home_rowNum>
    And user fills property details home page with "<Mandatory_NonMandatory>" fields for "<Application_Type>"
    And user reads data from the excel file "<PropertyDetailsWB>" under sheet "<PropertyDetails_otherDetails>" and row <PropertyDetails_otherDetails_rowNum>
    And user fills other details of property details with "<Mandatory_NonMandatory>" fields for "<Application_Type>"
    And user reads data from the excel file "<PropertyDetailsWB>" under sheet "<PropertyDetails_propertyAddress>" and row <PropertyDetails_propertyAddress_rowNum>
    And user fills property address with "<Mandatory_NonMandatory>" fields for "<Application_Type>"
    And user saves property details
    And user reads data from the excel file "<PropertyDetailsWB>" under sheet "<PropertyDetails_cersai>" and row <PropertyDetails_cersai_rowNum>
    When user fills Sub Registrar Office with "<var>" in CERSAI details
    Then Sub Registrar Office "<Throws_notThrows>" "<With_Error_Message>"

    Examples:
      | Loan_Type | var                        | Mandatory_NonMandatory | Throws_notThrows                   | With_Error_Message                | Application_Type    | Loan_Type | SourceDataFile       | SheetName | RowNumber | SourcingDetailsWB     | SourcingDetails_home | SourcingDetails_home_rowNum |  | PropertyDetailsWB     | PropertyDetails_home | PropertyDetails_home_rowNum | PropertyDetails_otherDetails | PropertyDetails_otherDetails_rowNum | PropertyDetails_propertyAddress | PropertyDetails_propertyAddress_rowNum | PropertyDetails_cersai | PropertyDetails_cersai_rowNum |
      | Home Loan | valid value                | mandatory              | does not throw any error           |                                   | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 0                             |
      | Home Loan | maximum length             | mandatory              | does not throw any error           | Number should have only 3 digits. | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 1                             |
      | Home Loan | both digits and characters | mandatory              | does not throw any error           | Please enter only Digits.         | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 2                             |
      | Home Loan | special characters         | mandatory              | throws an error with error message | Please enter only Digits.         | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 3                             |
      | Home Loan | space                      | mandatory              | does not throw any error           | Please enter only Digits.         | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 4                             |
      | Home Loan | negative value             | mandatory              | does not throw any error           | Please enter only Digits.         | Property Identified | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          |  | property_details.xlsx | home                 | 0                           | other_details                | 0                                   | property_address                | 0                                      | cersai_details         | 5                             |
