@Epic-Applicant_Information
@AppInfoAdoption
@AuthoredBy-vipin.kishor
@ReviewedByDEV
@Reconciled
#${ApplicantType:["indiv"]}

#FeatureID-ACAUTOCAS-158
Feature: Field validation with Agriculture Occupation in Employment Detail

  Background:
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "LoginDetailsCAS.xlsx" under "LoginData" and 0

  Scenario Outline: ACAUTOCAS-3819: Entering <Validity> <Field_Name> <Validity_Reason> in Agriculture Occupation at <ApplicationStage> in <ProductType>
    And user opens an application of "<ProductType>" product type as "<ApplicantType>" applicant at "<ApplicationStage>" for "<Category>" with "<Key>" from application grid
    And user navigates to applicant details page of "<ApplicationStage>"
    And click on view edit detailed info
    And user reads data from the excel file "<EmploymentDetailsWB>" under sheet "<EmploymentDetails_home>" and row <EmploymentDetails_home_rowNum>
    When user enters "<Validity>" "<Field_Name>" "<Validity_Reason>" for Agriculture in Employment Details
    Then application "<Throws_notThrows>" "<With_Error_Message>"

    # ${ProductType:["PF","HL","MAL","EDU","OMNI","CEQ","KCC","AGRL","FE","MHL","CV","CC","LAP"]}
    # ${ApplicationStage:["Lead Details","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    @Conventional
    @Release @Part-1
    @ImplementedBy-aman.nagarkoti
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Validity | Field_Name                    | Validity_Reason                           | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | Throws_notThrows                   | With_Error_Message                        | Category | Key |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | organization name             | with max characters                       | employment_details.xlsx | home                   | 75                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | organization name             | with characters                           | employment_details.xlsx | home                   | 77                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | organization name             | with digits                               | employment_details.xlsx | home                   | 78                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | organization name             | with spaces                               | employment_details.xlsx | home                   | 79                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | organization name             | with special characters ',/-&()!.$        | employment_details.xlsx | home                   | 80                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | organization name             | with special characters except ',/-&()!.$ | employment_details.xlsx | home                   | 81                            | throws an error with error message | Please input valid characters.            |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | years in years in occupation  | with characters                           | employment_details.xlsx | home                   | 82                            | throws an error with error message | Please enter only digits                 |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | years in years in occupation  | with special characters                   | employment_details.xlsx | home                   | 83                            | throws an error with error message | Please enter only digits                 |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | months in years in occupation | with characters                           | employment_details.xlsx | home                   | 84                            | throws an error with error message | Please enter only digits                 |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | months in years in occupation | with special characters                   | employment_details.xlsx | home                   | 85                            | throws an error with error message | Please enter only digits                 |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | months in years in occupation | with months more than 11                  | employment_details.xlsx | home                   | 86                            | throws an error with error message | Months cannot be equal / greater than 12. |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | remarks                       | with max characters                       | employment_details.xlsx | home                   | 87                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | remarks                       | with special characters                   | employment_details.xlsx | home                   | 88                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | remarks                       | with digits                               | employment_details.xlsx | home                   | 89                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | remarks                       | with alphanumeric characters              | employment_details.xlsx | home                   | 90                            | does_not_throw_any_error           |                                           |          |     |

    # ${ProductType:["IHF","IAF"]}
    # ${ApplicationStage:["Sourcing","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    @Islamic
    @Release
@Part-1
    @ImplementedBy-tanya
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Validity | Field_Name                    | Validity_Reason                           | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | Throws_notThrows                   | With_Error_Message                        | Category | Key |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | organization name             | with max characters                       | employment_details.xlsx | home                   | 75                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | organization name             | with characters                           | employment_details.xlsx | home                   | 77                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | organization name             | with digits                               | employment_details.xlsx | home                   | 78                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | organization name             | with spaces                               | employment_details.xlsx | home                   | 79                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | organization name             | with special characters ',/-&()!.$        | employment_details.xlsx | home                   | 80                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | organization name             | with special characters except ',/-&()!.$ | employment_details.xlsx | home                   | 81                            | throws an error with error message | Please input valid characters.            |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | years in years in occupation  | with characters                           | employment_details.xlsx | home                   | 82                            | throws an error with error message | Please enter only Digits.                 |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | years in years in occupation  | with special characters                   | employment_details.xlsx | home                   | 83                            | throws an error with error message | Please enter only Digits.                 |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | months in years in occupation | with characters                           | employment_details.xlsx | home                   | 84                            | throws an error with error message | Please enter only Digits.                 |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | months in years in occupation | with special characters                   | employment_details.xlsx | home                   | 85                            | throws an error with error message | Please enter only Digits.                 |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | months in years in occupation | with months more than 11                  | employment_details.xlsx | home                   | 86                            | throws an error with error message | Months cannot be equal / greater than 12. |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | remarks                       | with max characters                       | employment_details.xlsx | home                   | 87                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | remarks                       | with special characters                   | employment_details.xlsx | home                   | 88                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | remarks                       | with digits                               | employment_details.xlsx | home                   | 89                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | remarks                       | with alphanumeric characters              | employment_details.xlsx | home                   | 90                            | does_not_throw_any_error           |                                           |          |     |

    # ${ProductType:["IPF"]}
    # ${ApplicationStage:["Sourcing","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    # ${Category:["bonds"]}
    @Islamic
    @Release
@Part-1
    @ImplementedBy-tanya
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Validity | Field_Name                    | Validity_Reason                           | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | Throws_notThrows                   | With_Error_Message                        | Category   | Key |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | organization name             | with max characters                       | employment_details.xlsx | home                   | 75                            | does_not_throw_any_error           |                                           | <Category> |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | organization name             | with characters                           | employment_details.xlsx | home                   | 77                            | does_not_throw_any_error           |                                           | <Category> |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | organization name             | with digits                               | employment_details.xlsx | home                   | 78                            | does_not_throw_any_error           |                                           | <Category> |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | organization name             | with spaces                               | employment_details.xlsx | home                   | 79                            | does_not_throw_any_error           |                                           | <Category> |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | organization name             | with special characters ',/-&()!.$        | employment_details.xlsx | home                   | 80                            | does_not_throw_any_error           |                                           | <Category> |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | organization name             | with special characters except ',/-&()!.$ | employment_details.xlsx | home                   | 81                            | throws an error with error message | Please input valid characters.            | <Category> |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | years in years in occupation  | with characters                           | employment_details.xlsx | home                   | 82                            | throws an error with error message | Please enter only Digits.                 | <Category> |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | years in years in occupation  | with special characters                   | employment_details.xlsx | home                   | 83                            | throws an error with error message | Please enter only Digits.                 | <Category> |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | months in years in occupation | with characters                           | employment_details.xlsx | home                   | 84                            | throws an error with error message | Please enter only Digits.                 | <Category> |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | months in years in occupation | with special characters                   | employment_details.xlsx | home                   | 85                            | throws an error with error message | Please enter only Digits.                 | <Category> |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | months in years in occupation | with months more than 11                  | employment_details.xlsx | home                   | 86                            | throws an error with error message | Months cannot be equal / greater than 12. | <Category> |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | remarks                       | with max characters                       | employment_details.xlsx | home                   | 87                            | does_not_throw_any_error           |                                           | <Category> |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | remarks                       | with special characters                   | employment_details.xlsx | home                   | 88                            | does_not_throw_any_error           |                                           | <Category> |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | remarks                       | with digits                               | employment_details.xlsx | home                   | 89                            | does_not_throw_any_error           |                                           | <Category> |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | remarks                       | with alphanumeric characters              | employment_details.xlsx | home                   | 90                            | does_not_throw_any_error           |                                           | <Category> |     |
    @NotImplemented
     # ${ProductType:["FAS","GL","JLG","SHG"]}
    # ${ApplicationStage:["DDE","Recommendation","Credit Approval","Reconsideration"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Validity | Field_Name                    | Validity_Reason                           | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | Throws_notThrows                   | With_Error_Message                        | Category | Key |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | organization name             | with max characters                       | employment_details.xlsx | home                   | 75                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | organization name             | with characters                           | employment_details.xlsx | home                   | 77                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | organization name             | with digits                               | employment_details.xlsx | home                   | 78                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | organization name             | with spaces                               | employment_details.xlsx | home                   | 79                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | organization name             | with special characters ',/-&()!.$        | employment_details.xlsx | home                   | 80                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | organization name             | with special characters except ',/-&()!.$ | employment_details.xlsx | home                   | 81                            | throws an error with error message | Please input valid characters.            |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | years in years in occupation  | with characters                           | employment_details.xlsx | home                   | 82                            | throws an error with error message | Please enter only Digits.                 |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | years in years in occupation  | with special characters                   | employment_details.xlsx | home                   | 83                            | throws an error with error message | Please enter only Digits.                 |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | months in years in occupation | with characters                           | employment_details.xlsx | home                   | 84                            | throws an error with error message | Please enter only Digits.                 |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | months in years in occupation | with special characters                   | employment_details.xlsx | home                   | 85                            | throws an error with error message | Please enter only Digits.                 |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | invalid  | months in years in occupation | with months more than 11                  | employment_details.xlsx | home                   | 86                            | throws an error with error message | Months cannot be equal / greater than 12. |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | remarks                       | with max characters                       | employment_details.xlsx | home                   | 87                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | remarks                       | with special characters                   | employment_details.xlsx | home                   | 88                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | remarks                       | with digits                               | employment_details.xlsx | home                   | 89                            | does_not_throw_any_error           |                                           |          |     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | valid    | remarks                       | with alphanumeric characters              | employment_details.xlsx | home                   | 90                            | does_not_throw_any_error           |                                           |          |     |
