@Epic-Loan_Application_Details
#@AuthoredBy-vinod.pandey
@AuthoredBy-vipin.kishor
@ReviewedBy-None
@Release2
@ImplementedBy-aman.nagarkoti
@ReviewedByDEV
@Conventional
@Islamic
#FeatureID-ACAUTOCAS-4169
Feature:Property Address Details All field Validation of Property Details With Application Type As Identified Property Without Save for Phone number

  Scenario Outline: ACAUTOCAS-4985: Entering <Validity> <Field_Name> <Validity_Reason> in property address details for Phone number
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and <RowNumber>
    And user creates new application for "<Loan_Type>"
    And user reads data from the excel file "<SourcingDetailsWB>" under sheet "<SourcingDetails_home>" and row <SourcingDetails_home_rowNum>
    And user fills sourcing details
    And user reads data from the excel file "<PropertyDetailsWB>" under sheet "<PropertyDetails_home>" and row <PropertyDetails_home_rowNum>
    And user fills property details home page with "<Mandatory_NonMandatory>" fields for "<Application Type>"
    And user reads data from the excel file "<PropertyDetailsWB>" under sheet "<PropertyDetails_propertyAddress>" and row <PropertyDetails_propertyAddress_rowNum>
    When user enters "<Validity>" "<Field_Name>" "<Validity_Reason>" in property address details for Phone Number
    Then application "<Throws_notThrows>" at "<Field_Name>"

    Examples:
      | Mandatory_NonMandatory | Application Type    | Validity | Field_Name   | Validity_Reason        | Throws_notThrows               | Loan_Type | SourceDataFile       | SheetName | RowNumber | SourcingDetailsWB     | SourcingDetails_home | SourcingDetails_home_rowNum | PropertyDetailsWB     | PropertyDetails_propertyAddress | PropertyDetails_propertyAddress_rowNum | PropertyDetails_home | PropertyDetails_home_rowNum |
      | mandatory              | Property Identified | invalid  | Mobile Phone | with_characters        | display a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_address                | 16                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Mobile Phone | with_special_character | display a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_address                | 17                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Mobile Phone | with_alphanumeric      | display a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_address                | 18                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Mobile Phone | with_spaces            | display a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_address                | 19                                     | home                 | 0                           |
      | mandatory              | Property Identified | valid    | Mobile Phone |                        | does not throw any error       | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_address                | 20                                     | home                 | 0                           |
      | mandatory              | Property Identified | valid    | STD          |                        | does not throw any error       | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_address                | 21                                     | home                 | 0                           |
      | mandatory              | Property Identified | valid    | STD          | with_max_digits        | does not throw any error       | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_address                | 22                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | STD          | with_characters        | display a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_address                | 23                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | STD          | with_special_character | display a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_address                | 24                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | STD          | with_alphanumeric      | display a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_address                | 25                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | STD          | with_spaces            | display a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_address                | 26                                     | home                 | 0                           |
      | mandatory              | Property Identified | valid    | Number       |                        | does not throw any error       | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_address                | 27                                     | home                 | 0                           |
      | mandatory              | Property Identified | valid    | Number       | with_max_digits        | does not throw any error       | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_address                | 28                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Number       | with_characters        | display a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_address                | 29                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Number       | with_special_character | display a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_address                | 30                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Number       | with_alphanumeric      | display a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_address                | 31                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Number       | with_spaces            | display a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_address                | 32                                     | home                 | 0                           |
      | mandatory              | Property Identified | valid    | Extn         |                        | does not throw any error       | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_address                | 33                                     | home                 | 0                           |
      | mandatory              | Property Identified | valid    | Extn         | with_max_digits        | does not throw any error       | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_address                | 34                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Extn         | with_characters        | display a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_address                | 35                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Extn         | with_special_character | display a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_address                | 36                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Extn         | with_alphanumeric      | display a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_address                | 37                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Extn         | with_spaces            | display a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 0         | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_address                | 38                                     | home                 | 0                           |
