@Epic-Loan_Application_Details
#@AuthoredBy-vinod.pandey
@AuthoredBy-vipin.kishor
@ReviewedBy-None
@Release2
@ImplementedBy-aman.nagarkoti
@ReviewedByDev
#FeatureID-ACAUTOCAS-285
Feature:All Field Validation Of Customers Office Business Details In Personal Discussion Page

  Scenario Outline: ACAUTOCAS-1964:  Entering <Validity> <Field_Name> <Validity_Reason> in customers office business in Personal Discussion Page
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and <RowNumber>
    And user create new application of personal loan for individual
    And user reads data from the excel file "<PersonalInfoWB>" under sheet "<PersonalInfo_home>" and row <PersonalInfo_home_rowNum>
    And user fills home page of personal information
    And user reads data from the excel file "<SourcingDetailsWB>" under sheet "<SourcingDetails_home>" and row <SourcingDetails_home_rowNum>
    And user clicks on loan details tab
    And user fill sourcing details with "all" fields
    And user opens personal discussion tab
    And user reads data from the excel file "<PersonalDiscussionWB>" under sheet "<PersonalDiscussion_customersofficebusiness>" and row <PersonalDiscussion_rowNum>
    When user enters "<Validity>" "<Field_Name>" "<Validity_Reason>" in customers office business in personal discussion page
    Then application "<Throws_notThrows>" at "<Field_Name>" in customer office business in personal discussion

    Examples:
      | Validity | Field_Name                                 | Validity_Reason              | Throws_notThrows                 | SourceDataFile       | SheetName | RowNumber | SourcingDetailsWB     | SourcingDetails_home | SourcingDetails_home_rowNum | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | PersonalDiscussionWB     | PersonalDiscussion_customersofficebusiness | PersonalDiscussion_rowNum |
      | valid    | Total No Of Employees                      |                              | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 0                         |
      | valid    | Total No Of Employees                      | with maximum length          | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 1                         |
      | valid    | No. of Seen Employees                      |                              | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 2                         |
      | valid    | No. of Seen Employees                      | with maximum length          | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 3                         |
      | valid    | Office Size                                |                              | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 4                         |
      | valid    | Office Size                                | with maximum length          | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 5                         |
      | valid    | Number of Computers                        |                              | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 6                         |
      | valid    | Number of Computers                        | with maximum length          | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 7                         |
      | valid    | Number of Printers                         |                              | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 8                         |
      | valid    | Number of Printers                         | with maximum length          | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 9                         |
      | valid    | Number of Fax                              |                              | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 10                        |
      | valid    | Number of Fax                              | with maximum length          | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 11                        |
      | valid    | Number of Phone Lines                      |                              | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 12                        |
      | valid    | Number of Phone Lines                      | with maximum length          | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 13                        |
      | valid    | HUB Name                                   |                              | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 14                        |
      | valid    | HUB Name                                   | with maximum length          | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 15                        |
      | valid    | Distance                                   |                              | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 16                        |
      | valid    | Distance                                   | with maximum length          | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 17                        |
      | valid    | Business Background                        |                              | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 18                        |
      | valid    | Business Background                        | with maximum length          | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 19                        |
      | valid    | Years In Business As Driver                |                              | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 20                        |
      | valid    | Years In Business As Driver                | with maximum length          | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 21                        |
      | valid    | Years In Business As Group Family Business |                              | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 22                        |
      | valid    | Years In Business As Group Family Business | with maximum length          | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 23                        |
      | valid    | Years In Business As Self Transporter      |                              | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 24                        |
      | valid    | Years In Business As Self Transporter      | with maximum length          | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 25                        |
      | valid    | Total Years In Business                    |                              | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 26                        |
      | valid    | Total Years In Business                    | with maximum length          | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 27                        |
      | valid    | Years at Current Office                    |                              | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 28                        |
      | valid    | Years at Current Office                    | with maximum length          | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 29                        |
      | valid    | Office Size                                | with characters              | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 39                        |
      | valid    | Office Size                                | with alphanumeric characters | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 40                        |
      | valid    | Office Size                                | with space                   | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 41                        |
      | valid    | Distance                                   | with characters              | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 59                        |
      | valid    | Distance                                   | with alphanumeric characters | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 60                        |
      | valid    | Distance                                   | with space                   | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 61                        |

    @LoggedBug
    Examples:
      | Validity | Field_Name                                 | Validity_Reason              | Throws_notThrows        | SourceDataFile       | SheetName | RowNumber | SourcingDetailsWB     | SourcingDetails_home | SourcingDetails_home_rowNum | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | PersonalDiscussionWB     | PersonalDiscussion_customersofficebusiness | PersonalDiscussion_rowNum |
      | invalid  | Total No Of Employees                      | with special character       | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 30                        |
      | invalid  | Total No Of Employees                      | with characters              | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 31                        |
      | invalid  | Total No Of Employees                      | with alphanumeric characters | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 32                        |
      | invalid  | Total No Of Employees                      | with space                   | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 33                        |
      | invalid  | No. of Seen Employees                      | with special character       | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 34                        |
      | invalid  | No. of Seen Employees                      | with alphanumeric characters | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 36                        |
      | invalid  | No. of Seen Employees                      | with characters              | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 37                        |
      | invalid  | No. of Seen Employees                      | with space                   | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 37                        |
      | invalid  | Office Size                                | with special character       | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 38                        |
      | invalid  | Number of Computers                        | with special character       | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 42                        |
      | invalid  | Number of Computers                        | with characters              | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 43                        |
      | invalid  | Number of Computers                        | with alphanumeric characters | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 44                        |
      | invalid  | Number of Computers                        | with space                   | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 45                        |
      | invalid  | Number of Printers                         | with special character       | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 46                        |
      | invalid  | Number of Printers                         | with characters              | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 47                        |
      | invalid  | Number of Printers                         | with alphanumeric characters | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 48                        |
      | invalid  | Number of Printers                         | with space                   | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 49                        |
      | invalid  | Number of Fax                              | with special character       | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 50                        |
      | invalid  | Number of Fax                              | with characters              | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 51                        |
      | invalid  | Number of Fax                              | with alphanumeric characters | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 52                        |
      | invalid  | Number of Fax                              | with space                   | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 53                        |
      | invalid  | Number of Phone Lines                      | with special character       | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 54                        |
      | invalid  | Number of Phone Lines                      | with characters              | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 55                        |
      | invalid  | Number of Phone Lines                      | with alphanumeric characters | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 56                        |
      | invalid  | Number of Phone Lines                      | with space                   | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 57                        |
      | invalid  | Distance                                   | with special character       | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 58                        |
      | invalid  | Years In Business As Driver                | with special character       | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 62                        |
      | invalid  | Years In Business As Driver                | with characters              | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 63                        |
      | invalid  | Years In Business As Driver                | with alphanumeric characters | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 64                        |
      | invalid  | Years In Business As Driver                | with space                   | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 65                        |
      | invalid  | Years In Business As Group Family Business | with special character       | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 66                        |
      | invalid  | Years In Business As Group Family Business | with characters              | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 67                        |
      | invalid  | Years In Business As Group Family Business | with alphanumeric characters | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 68                        |
      | invalid  | Years In Business As Group Family Business | with space                   | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 69                        |
      | invalid  | Years In Business As Self Transporter      | with special character       | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 70                        |
      | invalid  | Years In Business As Self Transporter      | with characters              | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 71                        |
      | invalid  | Years In Business As Self Transporter      | with alphanumeric characters | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 72                        |
      | invalid  | Years In Business As Self Transporter      | with space                   | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 73                        |
      | invalid  | Total Years In Business                    | with special character       | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 74                        |
      | invalid  | Total Years In Business                    | with characters              | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 75                        |
      | invalid  | Total Years In Business                    | with alphanumeric characters | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 76                        |
      | invalid  | Total Years In Business                    | with space                   | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 77                        |
      | invalid  | Years at Current Office                    | with special character       | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 78                        |
      | invalid  | Years at Current Office                    | with characters              | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 79                        |
      | invalid  | Years at Current Office                    | with alphanumeric characters | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 80                        |
      | invalid  | Years at Current Office                    | with space                   | throws an error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | customers_officebusinessdetails            | 81                        |
