@Epic-Loan_Application_Details
@AuthoredBy-
@ReviewedBy-
@ImplementedBy-
@Conventional
@Islamic
@NotImplemented
@Test
Feature:Identified ready property field validation without save

  Scenario Outline: ACAUTOCAS-14075:  Saving identified property details without <FieldName>
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and <RowNumber>
    And user create new application for <Loan_Type>
    And user reads data from the excelFile "<LoanDetailsWB>" under sheet "<LoanDetails_sourcing>" and row <LoanDetails_sourcing_rowNum>
    And user fills and save sourcing details with "<Mandatory_All>"
    And user reads data from the excel file "<PropertyDetailsWB>" under sheet "<PropertyDetailsxxxx>" and row <property_rowNum>
    When user enters "<Validity>" "<Field_Name>" "<Validity_Reason>" in Identified Property Details
    Then application "<Throws_notThrows>" "<With_Error_Message>"

    Examples:
      | Validity | Field_Name                | Validity_Reason                       | Throws_notThrows                   | With_Error_Message                                                              | Loan_Type | Mandatory_All | SourceDataFile       | SheetName | RowNumber | PropertyDetailsWB | LoanDetails_sourcing | LoanDetails_sourcing_rowNum | LoanDetailWB | LoanDetails_propertyDetail | LoanDetails_propertyDetail_rowNum |
      | invalid  | Property Reference Number | with_special_characters_except_hyphen | throws an error with error message | Only alphanumeric characters, hyphen and spaces between characters are allowed. | Home loan | all           | LoginDetailsCAS.xlsx | LoginData | 7         |                   |                      |                             |              |                            |                                   |
      | valid    | Property Reference Number | with_special_character_hyphen         | does_not_throw_any_error           |                                                                                 | Home loan | all           | LoginDetailsCAS.xlsx | LoginData | 7         |                   |                      |                             |              |                            |                                   |
      | valid    | Property Reference Number | with_spaces                           | does_not_throw_any_error           |                                                                                 | Home loan | all           | LoginDetailsCAS.xlsx | LoginData | 7         |                   |                      |                             |              |                            |                                   |
      | valid    | Property Reference Number | with_max_characters                   | does_not_throw_any_error           |                                                                                 | Home loan | all           | LoginDetailsCAS.xlsx | LoginData | 7         |                   |                      |                             |              |                            |                                   |
      | valid    | Property Reference Number | with_alphanumeric                     | does_not_throw_any_error           |                                                                                 | Home loan | all           | LoginDetailsCAS.xlsx | LoginData | 7         |                   |                      |                             |              |                            |                                   |
      | valid    | Property Description      | all_type_of_characters                | does_not_throw_any_error           |                                                                                 | Home loan | all           | LoginDetailsCAS.xlsx | LoginData | 7         |                   |                      |                             |              |                            |                                   |
      | valid    | Property Description      | with_max_characters                   | does_not_throw_any_error           |                                                                                 | Home loan | all           | LoginDetailsCAS.xlsx | LoginData | 7         |                   |                      |                             |              |                            |                                   |
      | invalid  | Property Cost             | with_more_than_18_characters          | throws an error with error message | Only positive values and Upto 18 digits are allowed before decimal.             | Home loan | all           | LoginDetailsCAS.xlsx | LoginData | 7         |                   |                      |                             |              |                            |                                   |
      | invalid  | Property Cost             | with_characters                       | throws an error with error message | Invalid Amount                                                                  | Home loan | all           | LoginDetailsCAS.xlsx | LoginData | 7         |                   |                      |                             |              |                            |                                   |
      | invalid  | Property Cost             | with_alphanumeric                     | throws an error with error message | Invalid Amount                                                                  | Home loan | all           | LoginDetailsCAS.xlsx | LoginData | 7         |                   |                      |                             |              |                            |                                   |
      | invalid  | Property Cost             | with_special_characters               | throws an error with error message | Invalid Amount                                                                  | Home loan | all           | LoginDetailsCAS.xlsx | LoginData | 7         |                   |                      |                             |              |                            |                                   |
      | invalid  | Property Cost             | with_spaces                           | throws an error with error message | Invalid Amount                                                                  | Home loan | all           | LoginDetailsCAS.xlsx | LoginData | 7         |                   |                      |                             |              |                            |                                   |
      | valid    | Property Cost             |                                       |                                    |                                                                                 | Home loan | all           | LoginDetailsCAS.xlsx | LoginData | 7         |                   |                      |                             |              |                            |                                   |
      | invalid  | Approximate Property Cost | with_more_than_18_characters          | throws an error with error message | Only positive values and Upto 18 digits are allowed before decimal.             | Home loan | all           | LoginDetailsCAS.xlsx | LoginData | 7         |                   |                      |                             |              |                            |                                   |
      | invalid  | Approximate Property Cost | with_characters                       | throws an error with error message | Invalid Amount                                                                  | Home loan | all           | LoginDetailsCAS.xlsx | LoginData | 7         |                   |                      |                             |              |                            |                                   |
      | invalid  | Approximate Property Cost | with_alphanumeric                     | throws an error with error message | Invalid Amount                                                                  | Home loan | all           | LoginDetailsCAS.xlsx | LoginData | 7         |                   |                      |                             |              |                            |                                   |
      | invalid  | Approximate Property Cost | with_special_characters               | throws an error with error message | Invalid Amount                                                                  | Home loan | all           | LoginDetailsCAS.xlsx | LoginData | 7         |                   |                      |                             |              |                            |                                   |
      | invalid  | Approximate Property Cost | with_spaces                           | throws an error with error message | Invalid Amount                                                                  | Home loan | all           | LoginDetailsCAS.xlsx | LoginData | 7         |                   |                      |                             |              |                            |                                   |
      | valid    | Approximate Property Cost |                                       |                                    |                                                                                 | Home loan | all           | LoginDetailsCAS.xlsx | LoginData | 7         |                   |                      |                             |              |                            |                                   |




