@Epic-Loan_Application_Details
#@AuthoredBy-vinod.pandey
@AuthoredBy-vipin.kishor
@ReviewedBy-None
@Release1
@ImplementedBy-aman.nagarkoti
@ReviewedByDEV
@Conventional
@Islamic
#FeatureID-ACAUTOCAS-4169
Feature:All Field Validation Of Property And Registration Details With Application Type As Identified Property Without Save

  Scenario Outline: ACAUTOCAS-5001:  Entering <Validity> <Field_Name> <Validity_Reason> in agreement details
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and <RowNumber>
    And user creates new application for "<Loan_Type>"
    And user reads data from the excel file "<SourcingDetailsWB>" under sheet "<SourcingDetails_home>" and row <SourcingDetails_home_rowNum>
    And user fills sourcing details
    And user reads data from the excel file "<PropertyDetailsWB>" under sheet "<PropertyDetails_home>" and row <PropertyDetails_home_rowNum>
    And user fills property details home page with "<Mandatory_NonMandatory>" fields for "<Application Type>"
    And user reads data from the excel file "<PropertyDetailsWB>" under sheet "<PropertyDetails_propertyAndRegistration_details>" and row <PropertyDetails_propertyAndRegistration_details_rowNum>
    When user enters "<Validity>" "<Field_Name>" "<Validity_Reason>" in new agreement details
    Then application "<Throws_notThrows>" at "<Field_Name>" in new agreement details

    Examples:
      | Mandatory_NonMandatory | Application Type    | Validity | Field_Name                | Validity_Reason                          | Throws_notThrows              | Loan_Type | SourceDataFile       | SheetName | RowNumber | PropertyDetailsWB     | SourcingDetailsWB     | SourcingDetails_home | SourcingDetails_home_rowNum | PropertyDetailsWB     | PropertyDetails_propertyAndRegistration_details | PropertyDetails_propertyAndRegistration_details_rowNum | PropertyDetails_home | PropertyDetails_home_rowNum |
      | mandatory              | Property Identified | invalid  | Registration Number       | with special characters except /\,-.     | throws a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 1                                                      | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Registration Number       | with space                               | throws a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 2                                                      | home                 | 0                           |
      | mandatory              | Property Identified | valid    | Registration Number       | with digits only                         | does not throw any error      | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 3                                                      | home                 | 0                           |
      | mandatory              | Property Identified | valid    | Registration Number       | with characters                          | does not throw any error      | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 4                                                      | home                 | 0                           |
      | mandatory              | Property Identified | valid    | Registration Number       | with alphanumeric character              | does not throw any error      | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 5                                                      | home                 | 0                           |
      | mandatory              | Property Identified | valid    | Registration Number       | with maximum length input                | does not throw any error      | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 6                                                      | home                 | 0                           |
      | mandatory              | Property Identified | valid    | Registration Number       |                                          | does not throw any error      | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 7                                                      | home                 | 0                           |
      | mandatory              | Property Identified | valid    | Sale Deed Number          | with maximum length input                | does not throw any error      | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 8                                                      | home                 | 0                           |
      | mandatory              | Property Identified | valid    | Sale Deed Number          |                                          | does not throw any error      | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 9                                                      | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Registration Date         | with date greater than current date      | throws a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 10                                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Registration Date         | with date having year less than 1942     | throws a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 11                                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Registration Date         | with format except dd/MM/yyyy            | throws a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 12                                                     | home                 | 0                           |
      | mandatory              | Property Identified | valid    | Registration Date         |                                          | does not throw any error      | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 13                                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Sale Deed Date            | with date greater than current date      | throws a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 14                                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Sale Deed Date            | with date having year less than 1942     | throws a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 15                                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Sale Deed Date            | with format except dd/MM/yyyy            | throws a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 16                                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Sale Deed Date            | with date greater than registration date | throws a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 17                                                     | home                 | 0                           |
      | mandatory              | Property Identified | valid    | Sale Deed Date            |                                          | does not throw any error      | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 18                                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Agreement Value           | with special characters                  | throws a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 19                                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Agreement Value           | with characters                          | throws a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 20                                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Agreement Value           | with alphanumeric character              | throws a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 21                                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Agreement Value           | with more than maximum digits            | throws a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 22                                                     | home                 | 0                           |
      | mandatory              | Property Identified | valid    | Agreement Value           |                                          | does not throw any error      | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 23                                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Amenities Agreement Value | with special characters                  | throws a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 24                                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Amenities Agreement Value | with characters                          | throws a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 25                                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Amenities Agreement Value | with alphanumeric character              | throws a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 26                                                     | home                 | 0                           |
      | mandatory              | Property Identified | invalid  | Amenities Agreement Value | with more than maximum digits            | throws a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 27                                                     | home                 | 0                           |
      | mandatory              | Property Identified | valid    | Amenities Agreement Value |                                          | does not throw any error      | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 28                                                     | home                 | 0                           |
      | mandatory              | Property Identified | valid    | Remarks                   |                                          | does not throw any error      | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | sourcing_details.xlsx | home                 | 33                          | property_details.xlsx | property_&_registration_details                 | 29                                                     | home                 | 0                           |

  Scenario Outline: ACAUTOCAS-5002:  Entering <Validity> <Field_Name> <Validity_Reason> in property and registration details
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and <RowNumber>
    And user creates new application for "<Loan_Type>"
    And user reads data from the excel file "<SourcingDetailsWB>" under sheet "<SourcingDetails_home>" and row <SourcingDetails_home_rowNum>
    And user fills sourcing details
    And user reads data from the excel file "<PropertyDetailsWB>" under sheet "<PropertyDetails_home>" and row <PropertyDetails_home_rowNum>
    And user fills property details home page with "<Mandatory_NonMandatory>" fields for "<Application Type>"
    And user reads data from the excel file "<PropertyDetailsWB>" under sheet "<PropertyDetails_propertyAndRegistration_details>" and row <PropertyDetails_propertyAndRegistration_details_rowNum>
    When user enters "<Validity>" "<Field_Name>" "<Validity_Reason>" in agreement details
    Then application "<Throws_notThrows>" at "<Field_Name>" in agreement details

    Examples:
      | Mandatory_NonMandatory | Application Type    | Validity | Field_Name      | Validity_Reason | Throws_notThrows         | Loan_Type | SourceDataFile       | SheetName | RowNumber | PropertyDetailsWB     | PropertyDetails_home | PropertyDetails_home_rowNum | SourcingDetailsWB     | SourcingDetails_home | SourcingDetails_home_rowNum | PropertyDetails_propertyAndRegistration_details | PropertyDetails_propertyAndRegistration_details_rowNum |
      | mandatory              | Property Identified | valid    | Agreement Value |                 | does not throw any error | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | home                 | 0                           | sourcing_details.xlsx | home                 | 33                          | property_&_registration_details                 | 30                                                     |
      | mandatory              | Property Identified | valid    | Agreement Value | with max digits | does not throw any error | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | home                 | 0                           | sourcing_details.xlsx | home                 | 33                          | property_&_registration_details                 | 31                                                     |

    @LoggedBug
    Examples:
      | Mandatory_NonMandatory | Application Type    | Validity | Field_Name      | Validity_Reason              | Throws_notThrows              | Loan_Type | SourceDataFile       | SheetName | RowNumber | PropertyDetailsWB     | PropertyDetails_home | PropertyDetails_home_rowNum | SourcingDetailsWB     | SourcingDetails_home | SourcingDetails_home_rowNum | PropertyDetails_propertyAndRegistration_details | PropertyDetails_propertyAndRegistration_details_rowNum |
      | mandatory              | Property Identified | invalid  | Agreement Value | with characters              | throws a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | home                 | 0                           | sourcing_details.xlsx | home                 | 33                          | property_&_registration_details                 | 32                                                     |
      | mandatory              | Property Identified | invalid  | Agreement Value | with special characters      | throws a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | home                 | 0                           | sourcing_details.xlsx | home                 | 33                          | property_&_registration_details                 | 33                                                     |
      | mandatory              | Property Identified | invalid  | Agreement Value | with space                   | throws a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | home                 | 0                           | sourcing_details.xlsx | home                 | 33                          | property_&_registration_details                 | 34                                                     |
      | mandatory              | Property Identified | invalid  | Agreement Value | with alphanumeric characters | throws a proper error message | Home Loan | LoginDetailsCAS.xlsx | LoginData | 7         | property_details.xlsx | home                 | 0                           | sourcing_details.xlsx | home                 | 33                          | property_&_registration_details                 | 35                                                     |

