@Epic-Loan_Application_Details
@ReviewedBy-None
@AuthoredBy-ruchi.rawat
@OnHold
@ReviewedByGWT
@NotImplemented
@Conventional
@Islamic
Feature:Sourcing Details is used to capture the application sourcing details such as the Sourcing Channel, Product/Scheme applied for,
  Loan Amount Requested, Relationship Manager, Direct Selling Agency/ Team/ Agent etc

  Background:
    Given user with rights to Sourcing Details tab, and rights to specific branch and product, logs into the system and punches a new application


  Scenario Outline: ACAUTOCAS-3466:  Validate Application Creation Date
    And the user starts creating a "<LOB>" application
    When the user starts filling the sourcing details
    And tries entering the Application Creation Date
    Then creation date should be auto populated as the current date
    And creation date should be disabled

    Examples:
      | LOB           |
      | Personal Loan |
      | Auto Loan     |
      | All LOBs      |


# Application ID is auto generated by the system and this field gets populated automatically once the Application ID is generated on saving the Sourcing Details
#  or adding the primary applicant, which ever is done first


  Scenario Outline: ACAUTOCAS-3467:  Validate Application ID
    And the user starts creating a "<LOB>" application
    When the user starts filling the sourcing details
    And tries entering the Application ID
    Then Application ID should be disabled and null

    Examples:
      | LOB           |
      | Personal Loan |
      | Auto Loan     |
      | All LOBs      |


# For Applications being sourced from FinnOne Neo CAS UI, the product processor is stamped as Internal For applications sourced using application creation API
#  the product prcosseor is stamped as the system from which the application is sourced


  Scenario Outline: ACAUTOCAS-3468:  Validate Product Processor
    And the user starts creating a "<LOB>" application
    When the user starts filling the sourcing details
    And tries entering the Product Processor
    Then Product Processor should be auto populated as Internal
    And Product Processor should be disabled

    Examples:
      | LOB           |
      | Personal Loan |
      | Auto Loan     |
      | All LOBs      |


#Branch Risk Category is auto populated from Organization Branch Master for all sourcing channels basis the processing branch selected


  Scenario: ACAUTOCAS-2545: Validate Branch Risk Category
    And the user selects a processing branch
    When the user is filling the sourcing details
    Then the Branch risk category should auto populate as per maintenance done in Organization Branch Master
    And Branch Risk Category should be disabled

#Product Type is auto populated basis the LoB chosen in the Create Application link


  Scenario: ACAUTOCAS-2546:  Validate Product type
    And the user selects a LoB for creating a loan application from the Create application link
    When the user goes to the sourcing tab
    Then the product type populated in the product type field is the one selected in create application link
    And it is disabled

# Product field displays the default product if default product is maintained in product master else the user can select the product from the list
#  Product list is basis the logged in user, branch selected and product type



  Scenario: ACAUTOCAS-2547:  Validate the Product
    And the user selects a product type from the create application link
    When the user goes to the sourcing tab
    Then the product is populated as the default product maintained in Product Master as per Product Type
    And it is enabled


  Scenario: ACAUTOCAS-2548:  Validate the Product list available
    And the user selects a product type from the create application link
    When the user goes to the sourcing tab
    Then in the product field the user searches using "%%%"
    And the products available in the list are the ones mapped to the user in users masters
    And available for the selected branch and product type


  Scenario: ACAUTOCAS-2548:  Validate the Product list available
    And the user is associated to a business partner such as DSA
    And selects a product type from the create application link
    When the user goes to the sourcing tab
    Then in the product field the user searches using "%%%"
    And the products available in the list are the ones mapped to the user in Business Partners master
    And available for the selected branch and product type

# Scheme field displays the default Scheme if default Scheme is maintained in Scheme master else the user can select the Scheme from the list Scheme list is basis the logged in user, branch selected and product If no scheme is mapped then it means all schemes are mapped



  Scenario: ACAUTOCAS-2549:  Validate the Scheme
    And the user selects a product in the product field
    When the user goes to the scheme field
    Then the scheme is populated as the default scheme maintained in Scheme Master as per Product
    And it is enabled


  Scenario: ACAUTOCAS-2550:  Validate the Scheme list available
    And the user selects a product in the product field
    When the user goes to the scheme field
    Then in the scheme field the user searches using "%%%"
    And the schemes available in the list are the ones mapped to the user in users masters
    And available for the selected branch and product


  Scenario: ACAUTOCAS-2551:  Validate the scheme list available
    And the user is associated to a business partner such as DSA
    And selects a product in the product field
    When the user goes to the scheme field
    Then in the scheme field the user searches using "%%%"
    And the schemes available in the list are the ones mapped to the user in Business Partners master
    And available for the selected branch and product type


  Scenario: ACAUTOCAS-2552:  Validate the Lead CRM number
    And the user navigates to the sourcing tab
    When the user enters the Lead CRM number
    Then the value should get accepted

# Application Types available are New Application, Multi Asset Application, BT with Top up, BT without Top up and Top up without closure



  Scenario Outline: ACAUTOCAS-4649:  Validate that multi asset application is  not available in all LoBs except Auto Loan, Commercial Vehicle, Construction Equipment, Farm Equipment
    And Product Type is chosen as "<Var_ProductType>"
    When user navigates to sourcing tab
    And click on Application Type dropdown
    Then Multi Asset is not available as an option

    Examples:
      | Var_ProductType |
      | Personal Loan   |
      | Home Loan       |
      | LAP             |
      | Education Loan  |


  Scenario Outline: ACAUTOCAS-3470: Validate that multi asset application is available in the "<Var_ProductType>"
    And Product Type is chosen as "<Var_ProductType>"
    When user navigates to sourcing tab
    And click on Application Type dropdown
    Then Multi Asset is available as an option
    Examples:
      | Var_ProductType        |
      | Auto Loan              |
      | Commercial vehicle     |
      | Construction Equipment |
      | Farm Equipment         |

#Amount Requested


  Scenario: ACAUTOCAS-4765:  Validate Amount Requested
    And the user navigates to the sourcing tab
    When the user enters the amount requested
    Then the user should be able to enter amount greater than zero
    And the user should be able to enter amount in 19,2 format

#Image Based Processing checkbox can be marked for cases where image based data capturing is to be done Cases sourced from FinnOne Neo ECM, are marked as image based processing true



  Scenario: ACAUTOCAS-2553:  Tick the Image Based processing checkbox
    And the user navigates to the sourcing tab
    When the user checks the image based processing checkbox
    Then the image based processing should be marked true for the application
    And the image based processing column in application grid should display yes for the application
    And the checkbox should be enabled


# If Application Type is selected as Balance Transfer without Top up, Balance Transfer with Top up



  Scenario Outline: ACAUTOCAS-4650: Validate when the application type is selected as Balance Transfer without Top up, Loan Category field is displayed
    And the user navigates to the sourcing tab
    When the user selects the Application type as <Application_type>
    Then <Field_Name> is displayed for Capturing the <Field_Purpose>
    And the fields are enabled for selection

    Examples:
      | Field_Name         | Field_Purpose        | Application_type  |
      | Loan Category      | Category of the Loan | BT without Top up |
      | End Use of BT loan | End use of BT Loan   | BT without Top up |
      | Reason for BT      | Reason for BT        | BT without Top up |
      | Loan Category      | Category of the Loan | BT with Top up    |
      | End Use of BT loan | End use of BT Loan   | BT with Top up    |
      | Reason for BT      | Reason for BT        | BT with Top up    |


  Scenario: ACAUTOCAS-4766:  Validate the top up Amount field
    And the user navigates to the sourcing tab
    When the user selects the Application Type as Balance Transfer with Top up
    Then the Top up Amount field should be displayed for capturing the Top up amount requested
    And Amount should be an enterable money field
    And the default currency should be the scheme currency
    And the format should be 19,2

#Tenure is defaulted as the default tenure maintained in the Repayment Policy mapped to the scheme



  Scenario: ACAUTOCAS-2554:  Validate Tenure
    And the user navigates to the sourcing tab
    When the user selects the product, scheme
    And enters the amount requested
    Then the Tenure field should be defaulted as the value maintained in the repayment policy
    And the field should be enabled so that the user can change the value


  Scenario: ACAUTOCAS-2555:  Validate Tenure In
    And the user navigates to the sourcing tab
    When the user selects the product, scheme
    And enters the amount requested
    Then the Tenure In field should be defaulted as the value maintained in the repayment policy
    And the field should be disabled

# Rate is defaulted from the Repayment Policy, it is enabled and can be changed at sourcing



  Scenario: ACAUTOCAS-2556:  Validate the requested rate is defaulted from the repayment policy and it can be changed at sourcing
    And the user navigates to the sourcing tab
    When the user selects the product, scheme
    Then the rate is defaulted as per the repayment policy
    And it is editable
    And the user can change the rate

# Application purpose is used to capture the purpose for which the loan is being applied



  Scenario: ACAUTOCAS-2557:  Capturing the Application purpose
    And the user navigates to the sourcing tab
    When the user clicks on the application purpose dropdown
    Then the list of application purpose as per the maintenance in seed master LoanPurpose Dtype is displayed for selection as per the mapping with product type as parent code


  Scenario: ACAUTOCAS-2558:  Capturing the Application Purpose Description
    And the user navigates to the sourcing tab
    When the user goes to the application purpose description field
    Then the user can enter description using alphabets, numbers and special characters
    And the user can enter 4000 characters
    And the user can drag the text area to read

#Prioirty of the application as High, Medium, Low can be captured


  Scenario: ACAUTOCAS-2559:  Capture the Priority
    And the user navigates to the sourcing tab
    When the user selects the priority of the application
    Then the priority of the application should get marked
    And the priority should be visible on the application grid
    And the priority should be editable

#Distance from sourcing branch is captured to ascertain the distance of the loan branch from the applicants home or office to ensure that the loan is applied in a close by branch and there is no intention of fraud



  Scenario: ACAUTOCAS-2560:  Capture the distance from the sourcing branch
    And the user navigates to the sourcing tab
    When the user enters the distance from the sourcing branch
    Then the field should only allow capturing numeric value


  Scenario: ACAUTOCAS-2561:  Capture the Sourcing RM Name
    And the user navigates to the sourcing tab
    When the user selects the Sourcing RM Name
    Then the list should only display the RMs who are mapped to the Loan Branch, Product, Active and mapped in the Officer master


  Scenario: ACAUTOCAS-2562:  Auto population of the Reporting Supervisor Name
    And the user navigates to the sourcing tab
    When the user selects the RM
    Then the Reporting supervisor should get populated as the supervisor mapped to the RM in the Officer Master


  Scenario: ACAUTOCAS-2563:  Capturing the DST
    And the user navigates to the sourcing tab
    When the user selects the RM
    Then the DST list should display the DSTs mapped to the RM
    And the DST should be mapped to the Loan Branch, Product and Active


  Scenario: ACAUTOCAS-2564:  Capturing the CRE
    And the user navigates to the sourcing tab
    When the user selects the DST
    Then the CRE list should display the CREs mapped to the DST in the Tema Hierarchy Master


  Scenario: ACAUTOCAS-2565:  Capturing the Credit Officer
    And the user navigates to the sourcing tab
    When the user selects the RM
    Then the Credit Officer list should display the list of Credit Officers mapped to the RM in the Officer Master
    And the Credit Officer should be mapped to the Loan Branch, product and Active

#Subsidy is configurable for product type, the following fields are available for capturing the details, if configured - Subsidy Flag (Yes/No), Subsidy type, Subsidy Lock in Period, Subsidy Method (Rate Based/Amount Based)and Subsidy Rate Based/ Subsidy Amount Based


  Scenario Outline: ACAUTOCAS-3471:  Marking Subsidy as "<YesNo>"
    And the user navigates to the sourcing tab
    And subsidy is configured for "<Product_Type>"
    And Subsidy section is available on sourcing tab
    When the user selects the Subsidy Flag as Yes
    Then the other subsidy field should be enabled for data capturing
    Examples:
      | Product_Type   | YesNo |
      | Education Loan | Yes   |
      | Home Loan      | Yes   |
      | Education Loan | No    |
      | Home Loan      | No    |


  Scenario Outline: ACAUTOCAS-3472:  Capturing the Subsidy Type
    And the user navigates to the sourcing tab
    And subsidy is configured for "<Product_Type>"
    And Subsidy section is available on sourcing tab
    When the user selects the Subsidy Type from the list
    Then the subsidy type should get selected as per the maintenance for the Product type
    Examples:
      | Product_Type   |
      | Education Loan |
      | Home Loan      |


  Scenario Outline: ACAUTOCAS-3473:  Capturing the Subsidy Lock in Period
    And the user navigates to the sourcing tab
    And subsidy is configured for "<Product_Type>"
    And Subsidy section is available on sourcing tab
    When the user enters the subsidy Lock in period
    Then Lock in Period should get stored
    And Lock in Period should be a numeric field
    Examples:
      | Product_Type   |
      | Education Loan |
      | Home Loan      |

  Scenario Outline: ACAUTOCAS-3474:  Capturing the Subsidy Method
    And the user navigates to the sourcing tab
    And subsidy is configured for "<Product_Type>"
    And Subsidy section is available on sourcing tab
    When the user selects the Subsidy Method as Rate Based
    Then Subsidy Method should get stored
    And subsidy rate based field should be available for capturing the subsidy rate
    Examples:
      | Product_Type   |
      | Education Loan |
      | Home Loan      |

  Scenario Outline: ACAUTOCAS-3474:  Capturing the Subsidy Method
    And the user navigates to the sourcing tab
    And subsidy is configured for "<Product_Type>"
    And Subsidy section is available on sourcing tab
    When the user selects the Subsidy Method as Amount Based
    Then Subsidy Method should get stored
    And subsidy amount based field should be available for capturing the subsidy amount
    Examples:
      | Product_Type   |
      | Education Loan |
      | Home Loan      |


  Scenario: ACAUTOCAS-2566:  Sourcing channel is selected as Employee Referral
    And the user navigates to the sourcing tab
    When the Sourcing Channel is chosen as Employee Referral
    Then Employee Name and Employee No fields are visible for capturing the details of the employee who sourced the application


  Scenario: ACAUTOCAS-2567:  Sourcing channel is selected as Referral
    And the user navigates to the sourcing tab
    When the Sourcing Channel is chosen as Referral
    Then Referral Code and Referral Name fields are visible for capturing the details of the referral who sourced the application
    And the Referral code is filtered on the basis of Product mapped


  Scenario: ACAUTOCAS-2567:  Sourcing channel is selected as Referral
    And the user navigates to the sourcing tab
    When the Sourcing Channel is chosen as Referral
    And Referral Code is selected
    Then DSE Code and DSE Name fields are visible for capturing the details of the DSE mapped to the DSA who sourced the application
    And the DSE is filtered basis the Branch, Product and DSA mapped


  Scenario: ACAUTOCAS-2568:  Sourcing channel is selected as Connector
    And the user navigates to the sourcing tab
    When the Sourcing Channel is chosen as Connector
    Then Connector Code and Connector Name fields are visible for capturing the details of the connector who sourced the application
    And the Connector is filtered basis the Branch and Product mapped


  Scenario: ACAUTOCAS-2568:  Sourcing channel is selected as Connector
    And the user navigates to the sourcing tab
    When the Sourcing Channel is chosen as Connector
    And Connector Code is selected
    Then DSE Code and DSE Name fields are visible for capturing the details of the DSE mapped to the Connector who sourced the application
    And the DSE is filtered basis the Branch, Product and DSA mapped


#  Scenario: ACAUTOCAS-2569:  Sourcing channel is selected as Alternate Channel
#    And the user navigates to the sourcing tab
#    When the Sourcing Channel is chosen as Alternate Channel
#    Then the Alternate Channel Mode field is visible
#    And the user is able to select it from the dropdown
#
#
#  Scenario: ACAUTOCAS-2570:  Sourcing channel is selected as Branch
#    And the user navigates to the sourcing tab
#    When the Sourcing Channel is chosen as Branch
#    Then the Sourcing Branch field is visible
#    And the user is able to select it from the LoV


  Scenario: ACAUTOCAS-2571:  Sourcing channel is selected as SLI
    And the user navigates to the sourcing tab
    When the Sourcing Channel is chosen as SLI
    Then the village field is available
    And the villages If mapping available in User master, then from User master, else from Served villages in Organization Branch Master
    And the Village Risk Category is auto populated basis the village selected


  Scenario: ACAUTOCAS-2571:  Sourcing channel is selected as SLI
    And the user navigates to the sourcing tab
    When the Sourcing Channel is chosen as SLI
    Then the city field is available
    And the cities If mapping available in User master, then from User master, else from Served cities in Organization Branch Master
    And the City Risk Category is auto populated basis the city selected


#  Scenario: Sourcing channel is selected as SLI
#    And the user navigates to the sourcing tab
#    When the Sourcing Channel is chosen as SLI
#    Then the Work Area field is available
#    And the Work Area  If logged in user is SO, then the ones mapped to the SO in Work Area SO mapping
#    And if logged in user is RM, then the work areas mapped to the selected Village/ City
#    And if logged in user is CO or any other user, then all work areas mapped to the selected city/ village

#
#  Scenario: Sourcing channel is selected as SLI
#    And the user navigates to the sourcing tab
#    When the Sourcing Channel is chosen as SLI
#    Then the DCC User field is available
#    And the DCC User who would be conducting the DCC Execution Stage later on can be selected
#    And the DCC user filtration is basis the branch, village/ city, area, product, scheme and authority


  Scenario: ACAUTOCAS-2571:  Sourcing channel is selected as SLI
    And the user navigates to the sourcing tab
    When the Sourcing Channel is chosen as SLI
    Then either of village or city is mandatory to capture

#configsourcingpromocodeaccordionshow -- property for displaying the promo code section



  Scenario: ACAUTOCAS-2572:  Validate the promo codes basis the master mapping and manual addition
    And the configuration for promo code is on
    And the user navigates to the sourcing tab
    When the user clicks on the Promocode Details accordion
    And searches the Promo Code Name
    Then the promo codes basis the maintenance in the master should be available for selection
    And the user should be able to map multiple sales promo codes
    And the user should be able to map single credit promo code
    And the source should be displayed as manual if the promo code is applied manually
    And the description and promo type should be displayed basis the promo code applied


  Scenario: ACAUTOCAS-2573:  Validate the promo codes basis the master mapping and definition of rule matrix of Rule Matrix Type PromoCode
    And the configuration for promo code is on
    And the user navigates to the sourcing tab
    When the user clicks on the Promocode Details accordion
    And clicks on the Get Promo Code button
    Then the promo codes basis the maintenance in the rule matrix should be populated
    And the promo codes should be mapped basis the branch, product and scheme mapping
    And the user should be able to map promo codes manually
    And duplicates should be checked
    And the source should be displayed as Rule Matrix for the promo code applied by Rule Matrix
    And the description and promo type should be displayed basis the promo code applied

#LAN Linking feature can be used to link LANs and sharing this information with servicing system
# One application needs to be punched and moved to servicing system FinnOne Neo LMS



  Scenario: ACAUTOCAS-2574:  Link a valid LAN
    And the user navigates to the sourcing tab
    And clicks on the LAN Linking Details Accordion
    When the user enters a valid LAN in the LAN to be linked field
    And clicks on Validate LAN button
    Then the LAN should get validated
    And populate in the Linked LANs field


  Scenario: ACAUTOCAS-2575:  Link an invalid LAN
    And the user navigates to the sourcing tab
    And clicks on the LAN Linking Details Accordion
    When the user enters am invalid LAN in the LAN to be linked field
    And clicks on Validate LAN button
    Then the LAN should not get validated
    And should not populate in the Linked LANs field

#    Sourcing details credit card
#  @LeadDetails, @DDE, @CreditApproval, @Recommendation, @Reconsideration
#  @SourcingDetails
#  @RuchiGWT
#  @Release2
#
#  Feature:Sourcing Details is used to capture the application sourcing details such as the Sourcing Channel, Product/Scheme applied for,
#  Loan Amount Requested, Relationship Manager, Direct Selling Agency/ Team/ Agent. etc.
#
#  Background
#    And user with rights to Sourcing Details tab, and rights to specific branch and product, logs into the system and punches a new application.
#
  Scenario Outline: ACAUTOCAS-3475:  Validate Branch
    And the user starts creating a Credit Card application
    When the user starts filling the sourcing details
    And tries entering the Branch for "<RequestType>"
    Then Validate Branch should be auto populated as the logged in branch
    And the user should be able to change the branch to any other branch to which he has access

    Examples:
      | RequestType                      |
      | New Credit Card Application      |
      | Add-On Card                      |
      | Business Credit Card             |
      | Card Limit Update                |
      | Corporate Credit Card            |
      | Individual Business Credit Card  |
      | Individual Corporate Credit Card |


  Scenario Outline: ACAUTOCAS-3476:  Validate Application Form Number
    And the user starts creating a Credit Card application
    When the user starts filling the sourcing details
    And tries entering the Application Form Number for "<RequestType>"
    Then the user should be able to enter alphabets, numbers and hyphen
    And the user should not be able to enter more than 13 characters

    Examples:
      | RequestType                      |
      | New Credit Card Application      |
      | Add-On Card                      |
      | Business Credit Card             |
      | Card Limit Update                |
      | Corporate Credit Card            |
      | Individual Business Credit Card  |
      | Individual Corporate Credit Card |

#
#  Scenario Outline: Validate Date of receipt
#    And the user starts creating a Credit Card application
#    When the user starts filling the sourcing details
#    And tries entering the Date of receipt for "<RequestType>"
#    Then the user should be able to enter only valid date in dd/mm/yyyy format
#    And the user should not be able to enter any future date, only past or current date
#    And the user should not be able to enter a past date before the minimum year allowed as per configuration
##config.user.date.minimum.year
#
#    Examples:
#      | RequestType                      |
#      | New Credit Card Application      |
#      | Add-On Card                      |
#      | Business Credit Card             |
#      | Card Limit Update                |
#      | Corporate Credit Card            |
#      | Individual Business Credit Card  |
#      | Individual Corporate Credit Card |

#
#  Scenario Outline: Validate Application Creation Date
#    And the user starts creating a Credit Card application
#    When the user starts filling the sourcing details
#    And tries entering the Application Creation Date for "<RequestType>"
#    Then the date should be auto populated as the current date by default
#    And the user should be able to change the date to a past date in dd/mm/yyyy format
#    And the user should not be able to enter a past date before the minimum year allowed as per configuration
##config.user.date.minimum.year
#
#    Examples:
#      | RequestType                      |
#      | New Credit Card Application      |
#      | Add-On Card                      |
#      | Business Credit Card             |
#      | Card Limit Update                |
#      | Corporate Credit Card            |
#      | Individual Business Credit Card  |
#      | Individual Corporate Credit Card |

  Scenario Outline: ACAUTOCAS-3467:  Validate Application ID
    And the user starts creating a Credit Card application
    When the user starts filling the sourcing details
    And tries entering the Application ID for "<RequestType>"
    Then the field should be disabled and user should not be able to enter any data
    And the Application ID should be auto generated and auto populated by the system post sourcing details save or post applicant save whichever is done first

    Examples:
      | RequestType                      |
      | New Credit Card Application      |
      | Add-On Card                      |
      | Business Credit Card             |
      | Card Limit Update                |
      | Corporate Credit Card            |
      | Individual Business Credit Card  |
      | Individual Corporate Credit Card |


  Scenario Outline: ACAUTOCAS-3477:  Validate Lead ID
    And the user starts creating a Credit Card application
    When the user starts filling the sourcing details
    And tries entering the Lead ID for "<RequestType>"
    Then the field should be disabled and user should not be able to enter any data
    And the Lead ID should be auto populated for applications which are created by converting a Lead
    And Lead ID field should only be available for Request Type New Credit Card Application

    Examples:
      | RequestType                      |
      | New Credit Card Application      |
      | Add-On Card                      |
      | Business Credit Card             |
      | Card Limit Update                |
      | Corporate Credit Card            |
      | Individual Business Credit Card  |
      | Individual Corporate Credit Card |


  Scenario Outline: ACAUTOCAS-3478:  Validate Cross Sell Reference Number
    And the user starts creating a Credit Card application
    When the user starts filling the sourcing details
    And tries entering the Cross Sell Reference no for "<RequestType>"
    Then the field should be editable and user should be able to enter the data using alphabets, numbers, special characters and spaces
    And the Lead ID should be auto populated for applications which are created by converting a Lead
    And Lead ID field should only be available for Request Type New Credit Card Application

    Examples:
      | RequestType                      |
      | New Credit Card Application      |
      | Add-On Card                      |
      | Business Credit Card             |
      | Card Limit Update                |
      | Corporate Credit Card            |
      | Individual Business Credit Card  |
      | Individual Corporate Credit Card |


  Scenario Outline: ACAUTOCAS-3479:  Validate Priority
    And the user starts creating a Credit Card application
    When the user starts filling the sourcing details
    And tries entering the Priority for "<RequestType>"
    Then the field should be a dropdown with values as priority and non-priority
    And the user can select any value
# Priority Type dropdown values come from seed PriorityType and the ones mapped to parent code CC

    Examples:
      | RequestType                      |
      | New Credit Card Application      |
      | Add-On Card                      |
      | Business Credit Card             |
      | Card Limit Update                |
      | Corporate Credit Card            |
      | Individual Business Credit Card  |
      | Individual Corporate Credit Card |


  Scenario Outline: ACAUTOCAS-3480:  Validate Distance from sourcing branch in kms
    And the user starts creating a Credit Card application
    When the user starts filling the sourcing details
    And tries entering the Distance from sourcing branch in kms for "<RequestType>"
    Then the user should be able to enter a numeric field which accepts five digits before decimal and two after it

# it is the distance of any of the addresses of the customer from the processing branch

    Examples:
      | RequestType                      |
      | New Credit Card Application      |
      | Add-On Card                      |
      | Business Credit Card             |
      | Card Limit Update                |
      | Corporate Credit Card            |
      | Individual Business Credit Card  |
      | Individual Corporate Credit Card |


  Scenario Outline: ACAUTOCAS-3468:  Validate Product Processor
    And the user starts creating a Credit Card application
    When the user starts filling the sourcing details
    And tries entering the Product Processor for "<RequestType>"
    Then the user should not be able to change the value
    And Product Processor should be auto populated as INTERNAL for applications sourced through CAS UI
    And Product Processor should be auto populated basis the product processor from which it is sourced through service


    Examples:
      | RequestType                      |
      | New Credit Card Application      |
      | Add-On Card                      |
      | Business Credit Card             |
      | Card Limit Update                |
      | Corporate Credit Card            |
      | Individual Business Credit Card  |
      | Individual Corporate Credit Card |


  Scenario Outline: ACAUTOCAS-3481:  Validate Lead Number CRM
    And the user starts creating a Credit Card application
    When the user starts filling the sourcing details
    And tries entering the Lead Number CRM for "<RequestType>"
    Then the user should only be able to enter alphanumeric characters, underscore, hyphen and forward slash upto 25 characters

    Examples:
      | RequestType                      |
      | New Credit Card Application      |
      | Add-On Card                      |
      | Business Credit Card             |
      | Card Limit Update                |
      | Corporate Credit Card            |
      | Individual Business Credit Card  |
      | Individual Corporate Credit Card |


  Scenario Outline: ACAUTOCAS-3482:  Validate Branch Risk Category
    And the user starts creating a Credit Card application
    When the user starts filling the sourcing details
    And tries entering the Branch Risk Category for "<RequestType>"
    Then the user should not be able to do so
    And the field should be disabled and auto populated basis the Branch Risk Category maintained for the processing branch in the Organization Branches Master

    Examples:
      | RequestType                      |
      | New Credit Card Application      |
      | Add-On Card                      |
      | Business Credit Card             |
      | Card Limit Update                |
      | Corporate Credit Card            |
      | Individual Business Credit Card  |
      | Individual Corporate Credit Card |


  Scenario Outline: ACAUTOCAS-3483:  Validate Sourcing Channel
    And the user starts creating a Credit Card application
    When the user starts filling the sourcing details
    And tries selecting the Sourcing Channel for "<RequestType>"
    Then the user should be able to do so from a dropdown
    And the values should be <Sourcing Channel>

    Examples:
      | RequestType                      |
      | New Credit Card Application      |
      | Add-On Card                      |
      | Business Credit Card             |
      | Card Limit Update                |
      | Corporate Credit Card            |
      | Individual Business Credit Card  |
      | Individual Corporate Credit Card |
      | Sourcing Channel                 |
      | Internal                         |
      | DSA                              |
      | DST                              |
      | Connector                        |


  Scenario Outline: ACAUTOCAS-3484:  Validate Sourcing Branch
    And the user starts creating a Credit Card application
    When the user starts filling the sourcing details
    And tries selecting the Sourcing Branch for "<RequestType>"
    Then the user should be able to do so from the list of values
    And the values should be from Organization Branches MasterF

# All branches - to be checked

    Examples:
      | RequestType                      |
      | New Credit Card Application      |
      | Add-On Card                      |
      | Business Credit Card             |
      | Card Limit Update                |
      | Corporate Credit Card            |
      | Individual Business Credit Card  |
      | Individual Corporate Credit Card |


  Scenario Outline: ACAUTOCAS-3485:  Validate Cards RM Name
    And the user starts creating a Credit Card application
    When the user starts filling the sourcing details
    And tries selecting the Cards RM Name for "<RequestType>"
    Then the user should be able to do so from the dropdown
    And the RMs should be filtered basis branch, product and active RMs in Officer Master

    Examples:
      | RequestType                      |
      | New Credit Card Application      |
      | Add-On Card                      |
      | Business Credit Card             |
      | Card Limit Update                |
      | Corporate Credit Card            |
      | Individual Business Credit Card  |
      | Individual Corporate Credit Card |


  Scenario Outline: ACAUTOCAS-3486:  Validate Channel Type
    And the user starts creating a Credit Card application
    When the user starts filling the sourcing details
    And tries selecting the Channel Type for "<RequestType>"
    Then the user should be able to do so from the dropdown
    And the field channel type should appear only when the sourcing channel is selected as internal

# seed dtype ChannelType

    Examples:
      | RequestType                      |
      | New Credit Card Application      |
      | Add-On Card                      |
      | Business Credit Card             |
      | Card Limit Update                |
      | Corporate Credit Card            |
      | Individual Business Credit Card  |
      | Individual Corporate Credit Card |


  Scenario Outline: ACAUTOCAS-3487:  Validate Employee Name
    And the user starts creating a Credit Card application
    When the user starts filling the sourcing details
    And tries selecting the Employee Name for "<RequestType>"
    Then the user should be able to do so from the list of values
    And the field Employee Name should appear only when the sourcing channel is selected as internal

# Employer Name is maintained in Employer Number Upload Master

    Examples:
      | RequestType                      |
      | New Credit Card Application      |
      | Add-On Card                      |
      | Business Credit Card             |
      | Card Limit Update                |
      | Corporate Credit Card            |
      | Individual Business Credit Card  |
      | Individual Corporate Credit Card |


  Scenario Outline: ACAUTOCAS-3488:  Validate Employee Number
    And the user starts creating a Credit Card application
    When the user starts filling the sourcing details
    And selects the Employee Name for "<RequestType>"
    Then the employee number field should auto populate with the employee number of the selected employee name

# Employer Name is maintained in Employer Number Upload Master

    Examples:
      | RequestType                      |
      | New Credit Card Application      |
      | Add-On Card                      |
      | Business Credit Card             |
      | Card Limit Update                |
      | Corporate Credit Card            |
      | Individual Business Credit Card  |
      | Individual Corporate Credit Card |


















