@Epic-Loan_Application_Details
#@AuthoredBy-vinod.pandey
@AuthoredBy-vipin.kishor
@ReviewedBy-None
@Release2
@ImplementedBy-aman.nagarkoti
@ReviewedByDEV
#FeatureID-ACAUTOCAS-285
Feature:All Field Validation Of Other Business Details In Personal Discussion Page

  Scenario Outline: ACAUTOCAS-1970:  Entering <Validity> <Field_Name> <Validity_Reason> in other business details in Personal Discussion Page
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and <RowNumber>
    And user create new application of personal loan for individual
    And user reads data from the excel file "<PersonalInfoWB>" under sheet "<PersonalInfo_home>" and row <PersonalInfo_home_rowNum>
    And user fills home page of personal information
    And user reads data from the excel file "<SourcingDetailsWB>" under sheet "<SourcingDetails_home>" and row <SourcingDetails_home_rowNum>
    And user clicks on loan details tab
    And user fill sourcing details with "all" fields
    And user opens personal discussion tab
    And user reads data from the excel file "<PersonalDiscussionWB>" under sheet "<PersonalDiscussion_otherbusiness>" and row <PersonalDiscussion_rowNum>
    When user enters "<Validity>" "<Field_Name>" "<Validity_Reason>" in other business details in personal discussion page
    Then application "<Throws_notThrows>" at "<Field_Name>" in other business details in personal discussion

    Examples:
      | Validity | Field_Name                          | Validity_Reason                        | Throws_notThrows                 | SourceDataFile       | SheetName | RowNumber | SourcingDetailsWB     | SourcingDetails_home | SourcingDetails_home_rowNum | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | PersonalDiscussionWB     | PersonalDiscussion_otherbusiness | PersonalDiscussion_rowNum |
      | valid    | No.Of Employees Driver              |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 0                         |
      | valid    | No.Of Employees Driver              | with maximum length                    | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 1                         |
      | valid    | No.Of Employees Helper              |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 5                         |
      | valid    | No.Of Employees Helper              | with maximum length                    | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 6                         |
      | valid    | No.Of Employees Others              |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 11                        |
      | valid    | No.Of Employees Others              | with maximum length                    | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 12                        |
      | valid    | Monthly Expenses Salaries           |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 17                        |
      | invalid  | Monthly Expenses Salaries           | with more than 18 digit before decimal | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 18                        |
      | invalid  | Monthly Expenses Salaries           | with characters                        | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 19                        |
      | invalid  | Monthly Expenses Salaries           | with special characters                | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 20                        |
      | invalid  | Monthly Expenses Salaries           | with alphanumeric characters           | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 21                        |
      | invalid  | Monthly Expenses Salaries           | with space                             | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 22                        |
      | valid    | Monthly Expenses Others             |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 23                        |
      | invalid  | Monthly Expenses Others             | with more than 18 digit before decimal | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 24                        |
      | invalid  | Monthly Expenses Others             | with characters                        | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 25                        |
      | invalid  | Monthly Expenses Others             | with special characters                | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 26                        |
      | invalid  | Monthly Expenses Others             | with alphanumeric characters           | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 27                        |
      | invalid  | Monthly Expenses Others             | with space                             | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 28                        |
      | valid    | Any Seasonal Trend In Business Peak |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 29                        |
      | valid    | Any Seasonal Trend In Business Low  |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 30                        |
      | valid    | Any other source of Income Peak     |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 31                        |

    @LoggedBug
    Examples:
      | Validity | Field_Name             | Validity_Reason              | Throws_notThrows              | SourceDataFile       | SheetName | RowNumber | SourcingDetailsWB     | SourcingDetails_home | SourcingDetails_home_rowNum | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | PersonalDiscussionWB     | PersonalDiscussion_otherbusiness | PersonalDiscussion_rowNum |
      | invalid  | No.Of Employees Driver | with character               | throws a proper error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 2                         |
      | invalid  | No.Of Employees Driver | with alphanumeric characters | throws a proper error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 3                         |
      | invalid  | No.Of Employees Driver | special characters           | throws a proper error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 4                         |
      | invalid  | No.Of Employees Helper | with character               | throws a proper error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 7                         |
      | invalid  | No.Of Employees Helper | with alphanumeric characters | throws a proper error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 8                         |
      | invalid  | No.Of Employees Helper | special characters           | throws a proper error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 9                         |
      | invalid  | No.Of Employees Helper | with space                   | throws a proper error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 10                        |
      | invalid  | No.Of Employees Others | with character               | throws a proper error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 13                        |
      | invalid  | No.Of Employees Others | with alphanumeric characters | throws a proper error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 14                        |
      | invalid  | No.Of Employees Others | special characters           | throws a proper error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 15                        |
      | invalid  | No.Of Employees Others | with space                   | throws a proper error message | LoginDetailsCAS.xlsx | LoginData | 7         | sourcing_details.xlsx | home                 | 15                          | personal_information.xlsx | home              | 0                        | personal_discussion.xlsx | other_business_details           | 16                        |
