@Epic-Applicant_Information
@AuthoredBy-utkarsh.tiwari
@ImplementedBy-utkarsh.tiwari
@Release1
@Reconciled
@ReviewedByDEV
@AppInfoAdoption
@Perishable
#FeatureID-ACAUTOCAS-162
 #${ApplicantType:["indiv"]}
Feature: Validating Expense Details Mandatory Fields with Occupation as Salaried Without Save

  Scenario Outline: ACAUTOCAS-3869:  Validating Amount field in Expense Details with "<Validity>" data as <Amount_Field_Data>
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and <RowNumber>
    And user opens an application of "<ProductType>" product type as "<ApplicantType>" applicant at "<ApplicationStage>" for "<Category>" with "<key>" from application grid
    And user navigates to applicant details page of "<ApplicationStage>"
    And click on view edit detailed info
    And user reads data from the excel file "<PersonalInfoWB>" under sheet "<PersonalInfo_home>" and row <PersonalInfo_home_rowNum>
    And user fills home page of personal information
    And user saves personal information modal
    And user reads data from the excel file "<EmploymentDetailsWB>" under sheet "<EmploymentDetails_home>" and row <EmploymentDetails_home_rowNum>
    And user fills employment details without save and next for "Salaried"
    And user changes major occupation to "Salaried"
    And user reads data from the excel file "<FinancialDetailsWB>" under sheet "<FinancialDetails_expenseDetails>" and row <FinancialDetails_expenseDetails_rowNum>
    And user open financial details
    When user fills "<Amount_Field_Data>" in amount in expense details
    Then application "<Throws_NotThrows>" "<Error_Message>"
    @Islamic
    @Release
@Part-1
    #${ProductType:["IPF"]}
    # ${ApplicationStage:["Sourcing","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    #${Category:["bonds"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category   | key | Validity | Amount_Field_Data    | Throws_NotThrows         | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | FinancialDetailsWB     | FinancialDetails_expenseDetails | FinancialDetails_expenseDetails_rowNum | Error_Message                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | valid data           | does_not_throw_any_error | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 1                                      |                                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | max length           | does_not_throw_any_error | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 2                                      |                                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | more than max length | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 3                                      | Only positive values and Upto 18 digits are allowed before decimal. |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | both digits and char | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 4                                      | Invalid Amount.                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | negative number      | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 5                                      | Only positive values and Upto 18 digits are allowed before decimal. |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | special char         | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 6                                      | Invalid Amount.                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | space                | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 7                                      | Invalid Amount.                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | paise format         | does_not_throw_any_error | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 8                                      |                                                                     |
    @Islamic
    @Release
@Part-1
    #${ProductType:["IHF","IAF"]}
    # ${ApplicationStage:["Sourcing","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | Validity | Amount_Field_Data    | Throws_NotThrows         | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | FinancialDetailsWB     | FinancialDetails_expenseDetails | FinancialDetails_expenseDetails_rowNum | Error_Message                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | valid data           | does_not_throw_any_error | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 1                                      |                                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | max length           | does_not_throw_any_error | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 2                                      |                                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | more than max length | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 3                                      | Only positive values and Upto 18 digits are allowed before decimal. |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | both digits and char | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 4                                      | Invalid Amount.                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | negative number      | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 5                                      | Only positive values and Upto 18 digits are allowed before decimal. |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | special char         | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 6                                      | Invalid Amount.                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | space                | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 7                                      | Invalid Amount.                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | paise format         | does_not_throw_any_error | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 8                                      |                                                                     |
    @Conventional
    @Release @Part-1
    #${ ProductType : ["PF","HL","MAL","EDU","OMNI","CEQ","KCC","AGRL", "FE","MHL","CV","CC","LAP"]}
   # ${ApplicationStage:["Lead Details","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | Validity | Amount_Field_Data    | Throws_NotThrows         | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | FinancialDetailsWB     | FinancialDetails_expenseDetails | FinancialDetails_expenseDetails_rowNum | Error_Message                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | valid data           | does_not_throw_any_error | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 1                                      |                                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | max length           | does_not_throw_any_error | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 2                                      |                                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | more than max length | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 3                                      | Only positive values and Upto 18 digits are allowed before decimal. |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | both digits and char | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 4                                      | Invalid Amount.                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | negative number      | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 5                                      | Only positive values and Upto 18 digits are allowed before decimal. |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | special char         | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 6                                      | Invalid Amount.                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | space                | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 7                                      | Invalid Amount.                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | paise format         | does_not_throw_any_error | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 8                                      |                                                                     |
     # ${ProductType:["FAS","GL","JLG","SHG"]}
    # ${ApplicationStage:["DDE","Recommendation","Credit Approval"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | Validity | Amount_Field_Data    | Throws_NotThrows         | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | FinancialDetailsWB     | FinancialDetails_expenseDetails | FinancialDetails_expenseDetails_rowNum | Error_Message                                                       |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | valid data           | does_not_throw_any_error | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 1                                      |                                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | max length           | does_not_throw_any_error | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 2                                      |                                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | more than max length | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 3                                      | Only positive values and Upto 18 digits are allowed before decimal. |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | both digits and char | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 4                                      | Invalid Amount.                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | negative number      | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 5                                      | Only positive values and Upto 18 digits are allowed before decimal. |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | special char         | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 6                                      | Invalid Amount.                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | space                | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 7                                      | Invalid Amount.                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | paise format         | does_not_throw_any_error | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 8                                      |                                                                     |

  Scenario Outline: ACAUTOCAS-3870:  Validating Percentage field in Expense Details with "<Validity>" data as <Percentage_Field_Data>
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and <RowNumber>
    And user opens an application of "<ProductType>" product type as "<ApplicantType>" applicant at "<ApplicationStage>" for "<Category>" with "<key>" from application grid
    And user navigates to applicant details page of "<ApplicationStage>"
    And click on view edit detailed info
    And user reads data from the excel file "<PersonalInfoWB>" under sheet "<PersonalInfo_home>" and row <PersonalInfo_home_rowNum>
    And user fills home page of personal information
    And user saves personal information modal
    And user reads data from the excel file "<EmploymentDetailsWB>" under sheet "<EmploymentDetails_home>" and row <EmploymentDetails_home_rowNum>
    And user fills employment details without save and next for "Salaried"
    And user changes major occupation to "Salaried"
    And user reads data from the excel file "<FinancialDetailsWB>" under sheet "<FinancialDetails_expenseDetails>" and row <FinancialDetails_expenseDetails_rowNum>
    And user open financial details
    When user fills expense details with "<Percentage_Field_Data>" in percentage
    Then application "<Throws_NotThrows>" "<Error_Message>"
    @Islamic
    @Release
@Part-1
    #${ProductType:["IPF"]}
    # ${ApplicationStage:["Sourcing","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    #${Category:["bonds"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category   | key | Validity | Percentage_Field_Data      | Throws_NotThrows         | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | FinancialDetailsWB     | FinancialDetails_expenseDetails | FinancialDetails_expenseDetails_rowNum | Error_Message                                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | valid data                 | does_not_throw_any_error | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 9                                      |                                                                                   |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | more than 100 percent      | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 10                                     | Please enter valid percentage: upto 2 digits are allowed before and after decimal |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | both digits and char       | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 11                                     | Please enter valid percentage: upto 2 digits are allowed before and after decimal |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | negative number            | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 12                                     | Please enter valid percentage: upto 2 digits are allowed before and after decimal |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | special char               | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 13                                     | Please enter valid percentage: upto 2 digits are allowed before and after decimal |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | space                      | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 14                                     | Please enter valid percentage: upto 2 digits are allowed before and after decimal |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | invalid  | more than 2 decimal places | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 15                                     | Please enter valid percentage: upto 2 digits are allowed before and after decimal |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | 2 decimal places           | does_not_throw_any_error | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 16                                     |                                                                                   |
    @Islamic
    @Release
@Part-1
    #${ProductType:["IHF","IAF"]}
    # ${ApplicationStage:["Sourcing","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | Validity | Percentage_Field_Data      | Throws_NotThrows         | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | FinancialDetailsWB     | FinancialDetails_expenseDetails | FinancialDetails_expenseDetails_rowNum | Error_Message                                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | valid data                 | does_not_throw_any_error | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 9                                      |                                                                                   |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | more than 100 percent      | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 10                                     | Please enter valid percentage: upto 2 digits are allowed before and after decimal |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | both digits and char       | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 11                                     | Please enter valid percentage: upto 2 digits are allowed before and after decimal |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | negative number            | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 12                                     | Please enter valid percentage: upto 2 digits are allowed before and after decimal |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | special char               | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 13                                     | Please enter valid percentage: upto 2 digits are allowed before and after decimal |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | space                      | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 14                                     | Please enter valid percentage: upto 2 digits are allowed before and after decimal |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | more than 2 decimal places | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 15                                     | Please enter valid percentage: upto 2 digits are allowed before and after decimal |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | 2 decimal places           | does_not_throw_any_error | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 16                                     |                                                                                   |
    @Conventional
    @Release @Part-1
    #${ ProductType : ["PF","HL","MAL","EDU","OMNI","CEQ","KCC","AGRL", "FE","MHL","CV","CC","LAP"]}
   # ${ApplicationStage:["Lead Details","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | Validity | Percentage_Field_Data      | Throws_NotThrows         | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | FinancialDetailsWB     | FinancialDetails_expenseDetails | FinancialDetails_expenseDetails_rowNum | Error_Message                                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | valid data                 | does_not_throw_any_error | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 9                                      |                                                                                   |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | more than 100 percent      | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 10                                     | Please enter value between 0 to 100 upto 2 decimal places. |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | both digits and char       | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 11                                     | Please enter value between 0 to 100 upto 2 decimal places. |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | negative number            | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 12                                     | Please enter value between 0 to 100 upto 2 decimal places. |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | special char               | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 13                                     | Please enter value between 0 to 100 upto 2 decimal places. |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | space                      | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 14                                     | Please enter value between 0 to 100 upto 2 decimal places. |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | more than 2 decimal places | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 15                                     | Please enter value between 0 to 100 upto 2 decimal places. |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | 2 decimal places           | does_not_throw_any_error | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 16                                     |                                                                                   |
     # ${ProductType:["FAS","GL","JLG","SHG"]}
    # ${ApplicationStage:["DDE","Recommendation","Credit Approval"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | Validity | Percentage_Field_Data      | Throws_NotThrows         | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | FinancialDetailsWB     | FinancialDetails_expenseDetails | FinancialDetails_expenseDetails_rowNum | Error_Message                                                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | valid data                 | does_not_throw_any_error | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 9                                      |                                                                                   |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | more than 100 percent      | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 10                                     | Please enter value between 0 to 100 upto 2 decimal places. |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | both digits and char       | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 11                                     | Please enter value between 0 to 100 upto 2 decimal places. |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | negative number            | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 12                                     | Please enter value between 0 to 100 upto 2 decimal places. |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | special char               | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 13                                     | Please enter value between 0 to 100 upto 2 decimal places. |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | space                      | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 14                                     | Please enter value between 0 to 100 upto 2 decimal places. |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | invalid  | more than 2 decimal places | throws                   | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 15                                     | Please enter value between 0 to 100 upto 2 decimal places. |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | 2 decimal places           | does_not_throw_any_error | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 16                                     |                                                                                   |


  @longRun
    @Sanity
  Scenario Outline: ACAUTOCAS-3871:  Validating Net Amount combination with Expense Frequency with "<Validity>" data as <Expense_Frequency>
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and <RowNumber>
    And user opens an application of "<ProductType>" product type as "<ApplicantType>" applicant at "<ApplicationStage>" for "<Category>" with "<key>" from application grid
    And user navigates to applicant details page of "<ApplicationStage>"
    And click on view edit detailed info
    And user reads data from the excel file "<PersonalInfoWB>" under sheet "<PersonalInfo_home>" and row <PersonalInfo_home_rowNum>
    And user fills home page of personal information
    And user saves personal information modal
    And user reads data from the excel file "<EmploymentDetailsWB>" under sheet "<EmploymentDetails_home>" and row <EmploymentDetails_home_rowNum>
    And user fills employment details without save and next for "Salaried"
    And user changes major occupation to "Salaried"
    And user reads data from the excel file "<FinancialDetailsWB>" under sheet "<FinancialDetails_expenseDetails>" and row <FinancialDetails_expenseDetails_rowNum>
    And user open financial details
    When user fills expense details with expense frequency as "<Expense_Frequency>"
    Then net amount is calculated successfully for "<Expense_Frequency>" expense frequency
    @Islamic
    @Release
@Part-1
    #${ProductType:["IPF"]}
    # ${ApplicationStage:["Sourcing","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    #${Category:["bonds"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category   | key | Validity | Expense_Frequency | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | FinancialDetailsWB     | FinancialDetails_expenseDetails | FinancialDetails_expenseDetails_rowNum |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | monthly           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 17                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | quarterly         | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 18                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | annually          | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 19                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | bi-monthly        | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 20                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | fortnightly       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 21                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | half yearly       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 22                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | one time          | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 23                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | weekly            | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 24                                     |
    @Islamic
    @Release
@Part-1
    #${ProductType:["IHF","IAF"]}
    # ${ApplicationStage:["Sourcing","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | Validity | Expense_Frequency | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | FinancialDetailsWB     | FinancialDetails_expenseDetails | FinancialDetails_expenseDetails_rowNum |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | monthly           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 17                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | quarterly         | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 18                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | annually          | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 19                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | bi-monthly        | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 20                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | fortnightly       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 21                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | half yearly       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 22                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | one time          | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 23                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | weekly            | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 24                                     |
    @Conventional
    @Release @Part-1
    #${ ProductType : ["PF","HL","MAL","EDU","OMNI","CEQ","KCC","AGRL", "FE","MHL","CV","CC","LAP"]}
   # ${ApplicationStage:["Lead Details","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | Validity | Expense_Frequency | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | FinancialDetailsWB     | FinancialDetails_expenseDetails | FinancialDetails_expenseDetails_rowNum |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | monthly           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 17                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | quarterly         | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 18                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | annually          | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 19                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | bi-monthly        | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 20                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | fortnightly       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 21                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | half yearly       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 22                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | one time          | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 23                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | weekly            | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 24                                     |
     # ${ProductType:["FAS","GL","JLG","SHG"]}
    # ${ApplicationStage:["DDE","Recommendation","Credit Approval"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | Validity | Expense_Frequency | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | FinancialDetailsWB     | FinancialDetails_expenseDetails | FinancialDetails_expenseDetails_rowNum |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | monthly           | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 17                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | quarterly         | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 18                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | annually          | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 19                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | bi-monthly        | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 20                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | fortnightly       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 21                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | half yearly       | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 22                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | one time          | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 23                                     |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | weekly            | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 24                                     |


  Scenario Outline: ACAUTOCAS-3872:  Validating Net Amount combination with percentage and amount with "<Validity>" data
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and <RowNumber>
    And user opens an application of "<ProductType>" product type as "<ApplicantType>" applicant at "<ApplicationStage>" for "<Category>" with "<key>" from application grid
    And user navigates to applicant details page of "<ApplicationStage>"
    And click on view edit detailed info
    And user reads data from the excel file "<PersonalInfoWB>" under sheet "<PersonalInfo_home>" and row <PersonalInfo_home_rowNum>
    And user fills home page of personal information
    And user saves personal information modal
    And user reads data from the excel file "<EmploymentDetailsWB>" under sheet "<EmploymentDetails_home>" and row <EmploymentDetails_home_rowNum>
    And user fills employment details without save and next for "Salaried"
    And user changes major occupation to "Salaried"
    And user reads data from the excel file "<FinancialDetailsWB>" under sheet "<FinancialDetails_expenseDetails>" and row <FinancialDetails_expenseDetails_rowNum>
    And user open financial details
    When user fills expense details with "<Percentage_Amount>"
    Then net amount in combination with percentage and amount is calculated successfully for "<Expense_Frequency>" expense frequency

    @Islamic
    @Release
@Part-1
    #${ProductType:["IPF"]}
    # ${ApplicationStage:["Sourcing","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    #${Category:["bonds"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category   | key | Validity | Expense_Frequency | Percentage_Amount     | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | FinancialDetailsWB     | FinancialDetails_expenseDetails | FinancialDetails_expenseDetails_rowNum |
      | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | valid    | monthly           | percentage and amount | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 26                                     |

    @Islamic
    @Release
@Part-1
    #${ProductType:["IHF","IAF"]}
    # ${ApplicationStage:["Sourcing","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | Validity | Expense_Frequency | Percentage_Amount     | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | FinancialDetailsWB     | FinancialDetails_expenseDetails | FinancialDetails_expenseDetails_rowNum |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | monthly           | percentage and amount | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 26                                     |

    @Conventional
    @Release @Part-1
    #${ ProductType : ["PF","HL","MAL","EDU","OMNI","CEQ","KCC","AGRL", "FE","MHL","CV","CC","LAP"]}
   # ${ApplicationStage:["Lead Details","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | Validity | Expense_Frequency | Percentage_Amount     | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | FinancialDetailsWB     | FinancialDetails_expenseDetails | FinancialDetails_expenseDetails_rowNum |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | monthly           | percentage and amount | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 26                                     |

     # ${ProductType:["FAS","GL","JLG","SHG"]}
    # ${ApplicationStage:["DDE","Recommendation","Credit Approval"]}
    Examples:
      | ProductType   | ApplicantType   | ApplicationStage   | Category | key | Validity | Expense_Frequency | Percentage_Amount     | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | FinancialDetailsWB     | FinancialDetails_expenseDetails | FinancialDetails_expenseDetails_rowNum |
      | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | valid    | monthly           | percentage and amount | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 26                                     |


  Scenario Outline: ACAUTOCAS-3873:  Validating is commitment checkbox status with "<Validity>" data as "<Expense_Frequency>"
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and <RowNumber>
    And user opens an application of "<ProductType>" product type as "<ApplicantType>" applicant at "<ApplicationStage>" for "<Category>" with "<key>" from application grid
    And user navigates to applicant details page of "<ApplicationStage>"
    And click on view edit detailed info
    And user reads data from the excel file "<PersonalInfoWB>" under sheet "<PersonalInfo_home>" and row <PersonalInfo_home_rowNum>
    And user fills home page of personal information
    And user saves personal information modal
    And user reads data from the excel file "<EmploymentDetailsWB>" under sheet "<EmploymentDetails_home>" and row <EmploymentDetails_home_rowNum>
    And user fills employment details without save and next for "Salaried"
    And user changes major occupation to "Salaried"
    And user clicks on save and next of Employment Details
    And user reads data from the excel file "<FinancialDetailsWB>" under sheet "<FinancialDetails_expenseDetails>" and row <FinancialDetails_expenseDetails_rowNum>
    And user open financial details
    When user fills expense details with "<Mandatory_All>" fields
    Then is commitment checkbox is not editable

    @Islamic
    @Release
@Part-1
    #${ProductType:["IPF"]}
    # ${ApplicationStage:["Sourcing","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    #${Category:["bonds"]}
    Examples:
      | Validity | Expense_Frequency | ProductType   | ApplicantType   | ApplicationStage   | Category   | key | Mandatory_All | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | FinancialDetailsWB     | FinancialDetails_expenseDetails | FinancialDetails_expenseDetails_rowNum |
      | valid    | monthly           | <ProductType> | <ApplicantType> | <ApplicationStage> | <Category> |     | mandatory     | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 26                                     |

    @Islamic
    @Release
@Part-1
    #${ProductType:["IHF","IAF"]}
    # ${ApplicationStage:["Sourcing","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    Examples:
      | Validity | Expense_Frequency | ProductType   | ApplicantType   | ApplicationStage   | Category | key | Mandatory_All | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | FinancialDetailsWB     | FinancialDetails_expenseDetails | FinancialDetails_expenseDetails_rowNum |
      | valid    | monthly           | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | mandatory     | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 1                        | employment_details.xlsx | home                   | 136                           | financial_details.xlsx | expense_details                 | 26                                     |

    @Conventional
    @Release @Part-1
    #${ ProductType : ["PF","HL","MAL","EDU","OMNI","CEQ","KCC","AGRL", "FE","MHL","CV","CC","LAP"]}
   # ${ApplicationStage:["Lead Details","Login Acceptance","DDE","Recommendation","Credit Approval","Reconsideration"]}
    Examples:
      | Validity | Expense_Frequency | ProductType   | ApplicantType   | ApplicationStage   | Category | key | Mandatory_All | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | FinancialDetailsWB     | FinancialDetails_expenseDetails | FinancialDetails_expenseDetails_rowNum |
      | valid    | monthly           | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | mandatory     | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 26                                     |

     # ${ProductType:["FAS","GL","JLG","SHG"]}
    # ${ApplicationStage:["DDE","Recommendation","Credit Approval"]}
    Examples:
      | Validity | Expense_Frequency | ProductType   | ApplicantType   | ApplicationStage   | Category | key | Mandatory_All | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | EmploymentDetailsWB     | EmploymentDetails_home | EmploymentDetails_home_rowNum | FinancialDetailsWB     | FinancialDetails_expenseDetails | FinancialDetails_expenseDetails_rowNum |
      | valid    | monthly           | <ProductType> | <ApplicantType> | <ApplicationStage> |          |     | mandatory     | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | employment_details.xlsx | home                   | 130                           | financial_details.xlsx | expense_details                 | 26                                     |
