@Epic-Loan_Application_Details
#@AuthoredBy-vinod.pandey
@AuthoredBy-vipin.kishor
@ReviewedBy-None
@Release2
@ImplementedBy-aman.nagarkoti
@ReviewedByDev
@Conventional
  #FeatureID-ACAUTOCAS-285
Feature:All Field Validation Of Current Loan Requirement Details In Personal Discussion Page

  Scenario Outline: ACAUTOCAS-1959: Entering <Validity> <Field_Name> <Validity_Reason> in current loan requirement details in personal discussion page
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and <RowNumber>
    And user create new application of personal loan for individual
    And user reads data from the excel file "<PersonalInfoWB>" under sheet "<PersonalInfo_home>" and row <PersonalInfo_home_rowNum>
    And user fills home page of personal information
    And user reads data from the excel file "<SourcingDetailsWB>" under sheet "<SourcingDetails_home>" and row <SourcingDetails_home_rowNum>
    And user clicks on loan details tab
    And user fill sourcing details with "all" fields
    And user opens personal discussion tab
    And user reads data from the excel file "<PersonalDiscussionWB>" under sheet "<PersonalDiscussion_current_loan_requirement>" and row <PersonalDiscussion_rowNum>
    When user enters "<Validity>" "<Field_Name>" "<Validity_Reason>" in current loan requirement details in personal discussion page
    Then application "<Throws_notThrows>" at "<Field_Name>" in current loan requirement details in personal discussion

    Examples:
      | Validity | Field_Name                                           | Validity_Reason                        | Throws_notThrows                 | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | SourcingDetailsWB     | SourcingDetails_home | SourcingDetails_home_rowNum | PersonalDiscussionWB     | PersonalDiscussion_current_loan_requirement | PersonalDiscussion_rowNum |
      | valid    | Manufacturer For New Vehicle                         |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 0                         |
      | valid    | Manufacturer For New Vehicle                         | with maximum length                    | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 1                         |
      | valid    | Model For New Vehicle                                |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 2                         |
      | valid    | Model For New Vehicle                                | with maximum length                    | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 3                         |
      | valid    | Approximate Price                                    |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 4                         |
      | invalid  | Approximate Price                                    | with more than 18 digit before decimal | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 5                         |
      | invalid  | Approximate Price                                    | with characters                        | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 6                         |
      | invalid  | Approximate Price                                    | with special characters                | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 7                         |
      | invalid  | Approximate Price                                    | with alphanumeric characters           | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 8                         |
      | invalid  | Approximate Price                                    | with space                             | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 9                         |
      | valid    | Body Type                                            |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 10                        |
      | valid    | Body Type                                            | with maximum length                    | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 11                        |
      | valid    | Body Builder Name                                    |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 12                        |
      | valid    | Body Builder Name                                    | with maximum length                    | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 13                        |
      | valid    | Loan Amount Requested For Chassis                    |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 14                        |
      | invalid  | Loan Amount Requested For Chassis                    | with more than 18 digit before decimal | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 15                        |
      | invalid  | Loan Amount Requested For Chassis                    | with characters                        | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 16                        |
      | invalid  | Loan Amount Requested For Chassis                    | with special characters                | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 17                        |
      | invalid  | Loan Amount Requested For Chassis                    | with alphanumeric characters           | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 18                        |
      | invalid  | Loan Amount Requested For Chassis                    | with space                             | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 19                        |
      | valid    | Loan Amount Required For Body                        |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 20                        |
      | invalid  | Loan Amount Required For Body                        | with more than 18 digit before decimal | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 21                        |
      | invalid  | Loan Amount Required For Body                        | with characters                        | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 22                        |
      | invalid  | Loan Amount Required For Body                        | with special characters                | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 23                        |
      | invalid  | Loan Amount Required For Body                        | with alphanumeric characters           | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 24                        |
      | invalid  | Loan Amount Required For Body                        | with space                             | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 25                        |
      | valid    | Approximate Body Price                               |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 26                        |
      | invalid  | Approximate Body Price                               | with more than 18 digit before decimal | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 27                        |
      | invalid  | Approximate Body Price                               | with characters                        | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 28                        |
      | invalid  | Approximate Body Price                               | with special characters                | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 29                        |
      | invalid  | Approximate Body Price                               | with alphanumeric characters           | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 30                        |
      | invalid  | Approximate Body Price                               | with space                             | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 31                        |
      | valid    | Manufacturer For Used Vehicle                        |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 32                        |
      | valid    | Manufacturer For Used Vehicle                        | with maximum length                    | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 33                        |
      | valid    | Model For Used Vehicle                               |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 34                        |
      | valid    | Model For Used Vehicle                               | with maximum length                    | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 35                        |
      | valid    | Approximate Purchase Amount                          |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 36                        |
      | invalid  | Approximate Purchase Amount                          | with more than 18 digit before decimal | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 37                        |
      | invalid  | Approximate Purchase Amount                          | with characters                        | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 38                        |
      | invalid  | Approximate Purchase Amount                          | with special characters                | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 39                        |
      | invalid  | Approximate Purchase Amount                          | with alphanumeric characters           | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 40                        |
      | invalid  | Approximate Purchase Amount                          | with space                             | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 41                        |
      | valid    | Year Of Manufacturing                                |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 42                        |
      | valid    | KM Done                                              |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 43                        |
      | invalid  | KM Done                                              | with characters                        | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 44                        |
      | invalid  | KM Done                                              | with special characters                | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 45                        |
      | invalid  | KM Done                                              | with alphanumeric characters           | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 46                        |
      | invalid  | KM Done                                              | with space                             | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 47                        |
      | valid    | IDV Amount                                           |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 48                        |
      | invalid  | IDV Amount                                           | with more than 18 digit before decimal | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 49                        |
      | invalid  | IDV Amount                                           | with characters                        | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 50                        |
      | invalid  | IDV Amount                                           | with special characters                | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 51                        |
      | invalid  | IDV Amount                                           | with alphanumeric characters           | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 52                        |
      | invalid  | IDV Amount                                           | with space                             | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 53                        |
      | valid    | Insurance Expiry                                     |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 54                        |
      | valid    | Insurance Expiry                                     | with future date                       | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 55                        |
      | invalid  | Insurance Expiry                                     | with insurance year less than 1942     | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 56                        |
      | valid    | Loan Amount Required                                 |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 57                        |
      | invalid  | Loan Amount Required                                 | with more than 18 digit before decimal | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 58                        |
      | invalid  | Loan Amount Required                                 | with characters                        | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 59                        |
      | invalid  | Loan Amount Required                                 | with special characters                | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 60                        |
      | invalid  | Loan Amount Required                                 | with alphanumeric characters           | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 61                        |
      | invalid  | Loan Amount Required                                 | with space                             | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 62                        |
      | valid    | Brief Description Of Assets,Including Seller Details |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 63                        |
      | valid    | End use of Vehicle                                   |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 64                        |
      | valid    | End use of Funds for Refinance cases                 |                                        | does not throw any error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 65                        |
      | invalid  | Year Of Manufacturing                                | with characters                        | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 67                        |
      | invalid  | Year Of Manufacturing                                | with special characters                | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 68                        |
      | invalid  | Year Of Manufacturing                                | with alphanumeric characters           | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 69                        |
      | invalid  | Year Of Manufacturing                                | with space                             | throws a proper error message    | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 70                        |

    @LoggedBug
    Examples:
      | Validity | Field_Name            | Validity_Reason             | Throws_notThrows              | SourceDataFile       | SheetName | RowNumber | PersonalInfoWB            | PersonalInfo_home | PersonalInfo_home_rowNum | SourcingDetailsWB     | SourcingDetails_home | SourcingDetails_home_rowNum | PersonalDiscussionWB     | PersonalDiscussion_current_loan_requirement | PersonalDiscussion_rowNum |
      | invalid  | Year Of Manufacturing | with more than current year | throws a proper error message | LoginDetailsCAS.xlsx | LoginData | 7         | personal_information.xlsx | home              | 0                        | sourcing_details.xlsx | home                 | 15                          | personal_discussion.xlsx | current_loan_requirement                    | 66                        |
