@Epic-Recommendation
@AuthoredBy-harshita.nayak
@ReviewedBy-atul.mishra
@Release3
@ImplementedBy-aryan.jain
@ReviewedByDEV

Feature: Decision Justification Field validation in Recommendation

  #FeatureID-ACAUTOCAS-630
  Scenario Outline: ACAUTOCAS-4721: Validating Character Strength in Decision Justification Details <var> at Recommendation
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and 0
    And user opens an application at "<Var_Stage>" stage from application grid
    And user is on Decision Justification details at recommendation
    And user reads data from the excel file "<RecommendationWB>" under sheet "<Recommendation_default>" and row <Recommendation_default_rowNum>
    When user enters "<FieldName>" "<var>" in Decision Justification Details at recommendation for "<Applicant>" at "<Loan_Type>"
    Then "<FieldName>" field with "<Throws_notThrows>" "<ErrorMessage>" in Decision Justification Details at recommendation
    Examples:
      | Applicant      | FieldName          | Loan_Type     | var                       | SourceDataFile       | SheetName | Throws_notThrows         | ErrorMessage | Var_Stage                       | RecommendationWB    | Recommendation_default | Recommendation_default_rowNum |
      | Individual     | Character Strength | Home Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 0                             |
      | Individual     | Character Strength | Home Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 1                             |
      | Individual     | Character Strength | Home Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 2                             |
      | Individual     | Character Strength | Home Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 3                             |
      | Individual     | Character Strength | Home Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 4                             |
      | Individual     | Character Strength | Home Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 5                             |
      | Individual     | Character Strength | Home Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 6                             |
      | Individual     | Character Strength | Personal Loan | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 0                             |
      | Individual     | Character Strength | Personal Loan | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 1                             |
      | Individual     | Character Strength | Personal Loan | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 2                             |
      | Individual     | Character Strength | Personal Loan | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 3                             |
      | Individual     | Character Strength | Personal Loan | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 4                             |
      | Individual     | Character Strength | Personal Loan | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 5                             |
      | Individual     | Character Strength | Personal Loan | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 6                             |
      | Individual     | Character Strength | Auto Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 0                             |
      | Individual     | Character Strength | Auto Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 1                             |
      | Individual     | Character Strength | Auto Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 2                             |
      | Individual     | Character Strength | Auto Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 3                             |
      | Individual     | Character Strength | Auto Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 4                             |
      | Individual     | Character Strength | Auto Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 5                             |
      | Individual     | Character Strength | Auto Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 6                             |
      | Non-Individual | Character Strength | Home Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 0                             |
      | Non-Individual | Character Strength | Home Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 1                             |
      | Non-Individual | Character Strength | Home Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 2                             |
      | Non-Individual | Character Strength | Home Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 3                             |
      | Non-Individual | Character Strength | Home Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 4                             |
      | Non-Individual | Character Strength | Home Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 5                             |
      | Non-Individual | Character Strength | Home Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 6                             |
      | Non-Individual | Character Strength | Personal Loan | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 0                             |
      | Non-Individual | Character Strength | Personal Loan | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 1                             |
      | Non-Individual | Character Strength | Personal Loan | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 2                             |
      | Non-Individual | Character Strength | Personal Loan | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 3                             |
      | Non-Individual | Character Strength | Personal Loan | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 4                             |
      | Non-Individual | Character Strength | Personal Loan | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 5                             |
      | Non-Individual | Character Strength | Personal Loan | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 6                             |
      | Non-Individual | Character Strength | Auto Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 0                             |
      | Non-Individual | Character Strength | Auto Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 1                             |
      | Non-Individual | Character Strength | Auto Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 2                             |
      | Non-Individual | Character Strength | Auto Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 3                             |
      | Non-Individual | Character Strength | Auto Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 4                             |
      | Non-Individual | Character Strength | Auto Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 5                             |
      | Non-Individual | Character Strength | Auto Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 6                             |

  #FeatureID-ACAUTOCAS-630
  Scenario Outline: ACAUTOCAS-4722: Validating Character Weakness in Decision Justification Details <var> at Recommendation
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and 0
    And user opens an application at "<Var_Stage>" stage from application grid
    And user is on Decision Justification details at recommendation
    And user reads data from the excel file "<RecommendationWB>" under sheet "<Recommendation_default>" and row <Recommendation_default_rowNum>
    When user enters "<FieldName>" "<var>" in Decision Justification Details at recommendation for "<Applicant>" at "<Loan_Type>"
    Then "<FieldName>" field with "<Throws_notThrows>" "<ErrorMessage>" in Decision Justification Details at recommendation
    Examples:
      | Applicant      | FieldName          | Loan_Type     | var                       | SourceDataFile       | SheetName | Throws_notThrows         | ErrorMessage | Var_Stage                       | RecommendationWB    | Recommendation_default | Recommendation_default_rowNum |
      | Individual     | Character Weakness | Home Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 0                             |
      | Individual     | Character Weakness | Home Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 1                             |
      | Individual     | Character Weakness | Home Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 2                             |
      | Individual     | Character Weakness | Home Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 3                             |
      | Individual     | Character Weakness | Home Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 4                             |
      | Individual     | Character Weakness | Home Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 5                             |
      | Individual     | Character Weakness | Home Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 6                             |
      | Individual     | Character Weakness | Personal Loan | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 0                             |
      | Individual     | Character Weakness | Personal Loan | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 1                             |
      | Individual     | Character Weakness | Personal Loan | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 2                             |
      | Individual     | Character Weakness | Personal Loan | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 3                             |
      | Individual     | Character Weakness | Personal Loan | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 4                             |
      | Individual     | Character Weakness | Personal Loan | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 5                             |
      | Individual     | Character Weakness | Personal Loan | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 6                             |
      | Individual     | Character Weakness | Auto Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 0                             |
      | Individual     | Character Weakness | Auto Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 1                             |
      | Individual     | Character Weakness | Auto Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 2                             |
      | Individual     | Character Weakness | Auto Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 3                             |
      | Individual     | Character Weakness | Auto Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 4                             |
      | Individual     | Character Weakness | Auto Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 5                             |
      | Individual     | Character Weakness | Auto Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 6                             |
      | Non-Individual | Character Weakness | Home Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 0                             |
      | Non-Individual | Character Weakness | Home Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 1                             |
      | Non-Individual | Character Weakness | Home Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 2                             |
      | Non-Individual | Character Weakness | Home Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 3                             |
      | Non-Individual | Character Weakness | Home Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 4                             |
      | Non-Individual | Character Weakness | Home Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 5                             |
      | Non-Individual | Character Weakness | Home Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 6                             |
      | Non-Individual | Character Weakness | Personal Loan | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 0                             |
      | Non-Individual | Character Weakness | Personal Loan | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 1                             |
      | Non-Individual | Character Weakness | Personal Loan | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 2                             |
      | Non-Individual | Character Weakness | Personal Loan | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 3                             |
      | Non-Individual | Character Weakness | Personal Loan | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 4                             |
      | Non-Individual | Character Weakness | Personal Loan | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 5                             |
      | Non-Individual | Character Weakness | Personal Loan | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 6                             |
      | Non-Individual | Character Weakness | Auto Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 0                             |
      | Non-Individual | Character Weakness | Auto Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 1                             |
      | Non-Individual | Character Weakness | Auto Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 2                             |
      | Non-Individual | Character Weakness | Auto Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 3                             |
      | Non-Individual | Character Weakness | Auto Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 4                             |
      | Non-Individual | Character Weakness | Auto Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 5                             |
      | Non-Individual | Character Weakness | Auto Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 6                             |

  #FeatureID-ACAUTOCAS-630
  Scenario Outline: ACAUTOCAS-4723: Validating Capability Strength in Decision Justification Details <var> at Recommendation
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and 0
    And user opens an application at "<Var_Stage>" stage from application grid
    And user is on Decision Justification details at recommendation
    And user reads data from the excel file "<RecommendationWB>" under sheet "<Recommendation_default>" and row <Recommendation_default_rowNum>
    When user enters "<FieldName>" "<var>" in Decision Justification Details at recommendation for "<Applicant>" at "<Loan_Type>"
    Then "<FieldName>" field with "<Throws_notThrows>" "<ErrorMessage>" in Decision Justification Details at recommendation
    Examples:
      | Applicant      | FieldName           | Loan_Type     | var                       | SourceDataFile       | SheetName | Throws_notThrows         | ErrorMessage | Var_Stage                       | RecommendationWB    | Recommendation_default | Recommendation_default_rowNum |
      | Individual     | Capability Strength | Home Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 0                             |
      | Individual     | Capability Strength | Home Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 1                             |
      | Individual     | Capability Strength | Home Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 2                             |
      | Individual     | Capability Strength | Home Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 3                             |
      | Individual     | Capability Strength | Home Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 4                             |
      | Individual     | Capability Strength | Home Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 5                             |
      | Individual     | Capability Strength | Home Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 6                             |
      | Individual     | Capability Strength | Personal Loan | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 0                             |
      | Individual     | Capability Strength | Personal Loan | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 1                             |
      | Individual     | Capability Strength | Personal Loan | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 2                             |
      | Individual     | Capability Strength | Personal Loan | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 3                             |
      | Individual     | Capability Strength | Personal Loan | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 4                             |
      | Individual     | Capability Strength | Personal Loan | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 5                             |
      | Individual     | Capability Strength | Personal Loan | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 6                             |
      | Individual     | Capability Strength | Auto Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 0                             |
      | Individual     | Capability Strength | Auto Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 1                             |
      | Individual     | Capability Strength | Auto Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 2                             |
      | Individual     | Capability Strength | Auto Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 3                             |
      | Individual     | Capability Strength | Auto Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 4                             |
      | Individual     | Capability Strength | Auto Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 5                             |
      | Individual     | Capability Strength | Auto Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 6                             |
      | Non-Individual | Capability Strength | Home Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 0                             |
      | Non-Individual | Capability Strength | Home Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 1                             |
      | Non-Individual | Capability Strength | Home Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 2                             |
      | Non-Individual | Capability Strength | Home Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 3                             |
      | Non-Individual | Capability Strength | Home Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 4                             |
      | Non-Individual | Capability Strength | Home Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 5                             |
      | Non-Individual | Capability Strength | Home Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 6                             |
      | Non-Individual | Capability Strength | Personal Loan | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 0                             |
      | Non-Individual | Capability Strength | Personal Loan | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 1                             |
      | Non-Individual | Capability Strength | Personal Loan | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 2                             |
      | Non-Individual | Capability Strength | Personal Loan | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 3                             |
      | Non-Individual | Capability Strength | Personal Loan | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 4                             |
      | Non-Individual | Capability Strength | Personal Loan | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 5                             |
      | Non-Individual | Capability Strength | Personal Loan | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 6                             |
      | Non-Individual | Capability Strength | Auto Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 0                             |
      | Non-Individual | Capability Strength | Auto Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 1                             |
      | Non-Individual | Capability Strength | Auto Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 2                             |
      | Non-Individual | Capability Strength | Auto Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 3                             |
      | Non-Individual | Capability Strength | Auto Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 4                             |
      | Non-Individual | Capability Strength | Auto Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 5                             |
      | Non-Individual | Capability Strength | Auto Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 6                             |

  #FeatureID-ACAUTOCAS-630
  Scenario Outline: ACAUTOCAS-4724: Validating Capability Weakness in Decision Justification Details <var> at Recommendation
    Given user is on CAS Login Page
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and 0
    And user opens an application at "<Var_Stage>" stage from application grid
    And user is on Decision Justification details at recommendation
    And user reads data from the excel file "<RecommendationWB>" under sheet "<Recommendation_default>" and row <Recommendation_default_rowNum>
    When user enters "<FieldName>" "<var>" in Decision Justification Details at recommendation for "<Applicant>" at "<Loan_Type>"
    Then "<FieldName>" field with "<Throws_notThrows>" "<ErrorMessage>" in Decision Justification Details at recommendation
    Examples:
      | Applicant      | FieldName           | Loan_Type     | var                       | SourceDataFile       | SheetName | Throws_notThrows         | ErrorMessage | Var_Stage                       | RecommendationWB    | Recommendation_default | Recommendation_default_rowNum |
      | Individual     | Capability Weakness | Home Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 0                             |
      | Individual     | Capability Weakness | Home Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 1                             |
      | Individual     | Capability Weakness | Home Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 2                             |
      | Individual     | Capability Weakness | Home Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 3                             |
      | Individual     | Capability Weakness | Home Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 4                             |
      | Individual     | Capability Weakness | Home Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 5                             |
      | Individual     | Capability Weakness | Home Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 6                             |
      | Individual     | Capability Weakness | Personal Loan | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 0                             |
      | Individual     | Capability Weakness | Personal Loan | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 1                             |
      | Individual     | Capability Weakness | Personal Loan | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 2                             |
      | Individual     | Capability Weakness | Personal Loan | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 3                             |
      | Individual     | Capability Weakness | Personal Loan | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 4                             |
      | Individual     | Capability Weakness | Personal Loan | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 5                             |
      | Individual     | Capability Weakness | Personal Loan | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 6                             |
      | Individual     | Capability Weakness | Auto Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 0                             |
      | Individual     | Capability Weakness | Auto Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 1                             |
      | Individual     | Capability Weakness | Auto Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 2                             |
      | Individual     | Capability Weakness | Auto Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 3                             |
      | Individual     | Capability Weakness | Auto Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 4                             |
      | Individual     | Capability Weakness | Auto Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 5                             |
      | Individual     | Capability Weakness | Auto Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 6                             |
      | Non-Individual | Capability Weakness | Home Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 0                             |
      | Non-Individual | Capability Weakness | Home Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 1                             |
      | Non-Individual | Capability Weakness | Home Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 2                             |
      | Non-Individual | Capability Weakness | Home Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 3                             |
      | Non-Individual | Capability Weakness | Home Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 4                             |
      | Non-Individual | Capability Weakness | Home Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 5                             |
      | Non-Individual | Capability Weakness | Home Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 6                             |
      | Non-Individual | Capability Weakness | Personal Loan | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 0                             |
      | Non-Individual | Capability Weakness | Personal Loan | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 1                             |
      | Non-Individual | Capability Weakness | Personal Loan | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 2                             |
      | Non-Individual | Capability Weakness | Personal Loan | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 3                             |
      | Non-Individual | Capability Weakness | Personal Loan | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 4                             |
      | Non-Individual | Capability Weakness | Personal Loan | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 5                             |
      | Non-Individual | Capability Weakness | Personal Loan | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 6                             |
      | Non-Individual | Capability Weakness | Auto Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 0                             |
      | Non-Individual | Capability Weakness | Auto Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 1                             |
      | Non-Individual | Capability Weakness | Auto Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 2                             |
      | Non-Individual | Capability Weakness | Auto Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 3                             |
      | Non-Individual | Capability Weakness | Auto Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 4                             |
      | Non-Individual | Capability Weakness | Auto Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 5                             |
      | Non-Individual | Capability Weakness | Auto Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 6                             |

  #FeatureID-ACAUTOCAS-630
  Scenario Outline: ACAUTOCAS-4725: Validating Collateral Strength in Decision Justification Details <var> at Recommendation
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and 0
    And user opens an application at "<Var_Stage>" stage from application grid
    And user is on Decision Justification details at recommendation
    And user reads data from the excel file "<RecommendationWB>" under sheet "<Recommendation_default>" and row <Recommendation_default_rowNum>
    When user enters "<FieldName>" "<var>" in Decision Justification Details at recommendation for "<Applicant>" at "<Loan_Type>"
    Then "<FieldName>" field with "<Throws_notThrows>" "<ErrorMessage>" in Decision Justification Details at recommendation
    Examples:
      | Applicant      | FieldName           | Loan_Type     | var                       | SourceDataFile       | SheetName | Throws_notThrows         | ErrorMessage | Var_Stage                       | RecommendationWB    | Recommendation_default | Recommendation_default_rowNum |
      | Individual     | Collateral Strength | Home Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 0                             |
      | Individual     | Collateral Strength | Home Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 1                             |
      | Individual     | Collateral Strength | Home Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 2                             |
      | Individual     | Collateral Strength | Home Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 3                             |
      | Individual     | Collateral Strength | Home Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 4                             |
      | Individual     | Collateral Strength | Home Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 5                             |
      | Individual     | Collateral Strength | Home Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 6                             |
      | Individual     | Collateral Strength | Personal Loan | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 0                             |
      | Individual     | Collateral Strength | Personal Loan | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 1                             |
      | Individual     | Collateral Strength | Personal Loan | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 2                             |
      | Individual     | Collateral Strength | Personal Loan | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 3                             |
      | Individual     | Collateral Strength | Personal Loan | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 4                             |
      | Individual     | Collateral Strength | Personal Loan | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 5                             |
      | Individual     | Collateral Strength | Personal Loan | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 6                             |
      | Individual     | Collateral Strength | Auto Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 0                             |
      | Individual     | Collateral Strength | Auto Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 1                             |
      | Individual     | Collateral Strength | Auto Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 2                             |
      | Individual     | Collateral Strength | Auto Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 3                             |
      | Individual     | Collateral Strength | Auto Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 4                             |
      | Individual     | Collateral Strength | Auto Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 5                             |
      | Individual     | Collateral Strength | Auto Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 6                             |
      | Non-Individual | Collateral Strength | Home Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 0                             |
      | Non-Individual | Collateral Strength | Home Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 1                             |
      | Non-Individual | Collateral Strength | Home Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 2                             |
      | Non-Individual | Collateral Strength | Home Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 3                             |
      | Non-Individual | Collateral Strength | Home Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 4                             |
      | Non-Individual | Collateral Strength | Home Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 5                             |
      | Non-Individual | Collateral Strength | Home Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 6                             |
      | Non-Individual | Collateral Strength | Personal Loan | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 0                             |
      | Non-Individual | Collateral Strength | Personal Loan | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 1                             |
      | Non-Individual | Collateral Strength | Personal Loan | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 2                             |
      | Non-Individual | Collateral Strength | Personal Loan | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 3                             |
      | Non-Individual | Collateral Strength | Personal Loan | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 4                             |
      | Non-Individual | Collateral Strength | Personal Loan | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 5                             |
      | Non-Individual | Collateral Strength | Personal Loan | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 6                             |
      | Non-Individual | Collateral Strength | Auto Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 0                             |
      | Non-Individual | Collateral Strength | Auto Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 1                             |
      | Non-Individual | Collateral Strength | Auto Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 2                             |
      | Non-Individual | Collateral Strength | Auto Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 3                             |
      | Non-Individual | Collateral Strength | Auto Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 4                             |
      | Non-Individual | Collateral Strength | Auto Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 5                             |
      | Non-Individual | Collateral Strength | Auto Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 6                             |

  #FeatureID-ACAUTOCAS-630
  Scenario Outline: ACAUTOCAS-4726: Validating Collateral Weakness in Decision Justification Details <var> at Recommendation
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and 0
    And user opens an application at "<Var_Stage>" stage from application grid
    And user is on Decision Justification details at recommendation
    And user reads data from the excel file "<RecommendationWB>" under sheet "<Recommendation_default>" and row <Recommendation_default_rowNum>
    When user enters "<FieldName>" "<var>" in Decision Justification Details at recommendation for "<Applicant>" at "<Loan_Type>"
    Then "<FieldName>" field with "<Throws_notThrows>" "<ErrorMessage>" in Decision Justification Details at recommendation
    Examples:
      | Applicant      | FieldName           | Loan_Type     | var                       | SourceDataFile       | SheetName | Throws_notThrows         | ErrorMessage | Var_Stage                       | RecommendationWB    | Recommendation_default | Recommendation_default_rowNum |
      | Individual     | Collateral Weakness | Home Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 0                             |
      | Individual     | Collateral Weakness | Home Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 1                             |
      | Individual     | Collateral Weakness | Home Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 2                             |
      | Individual     | Collateral Weakness | Home Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 3                             |
      | Individual     | Collateral Weakness | Home Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 4                             |
      | Individual     | Collateral Weakness | Home Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 5                             |
      | Individual     | Collateral Weakness | Home Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 6                             |
      | Individual     | Collateral Weakness | Personal Loan | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 0                             |
      | Individual     | Collateral Weakness | Personal Loan | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 1                             |
      | Individual     | Collateral Weakness | Personal Loan | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 2                             |
      | Individual     | Collateral Weakness | Personal Loan | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 3                             |
      | Individual     | Collateral Weakness | Personal Loan | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 4                             |
      | Individual     | Collateral Weakness | Personal Loan | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 5                             |
      | Individual     | Collateral Weakness | Personal Loan | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation                  | recommendation.xlsx | decision_justification | 6                             |
      | Individual     | Collateral Weakness | Auto Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 0                             |
      | Individual     | Collateral Weakness | Auto Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 1                             |
      | Individual     | Collateral Weakness | Auto Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 2                             |
      | Individual     | Collateral Weakness | Auto Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 3                             |
      | Individual     | Collateral Weakness | Auto Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 4                             |
      | Individual     | Collateral Weakness | Auto Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 5                             |
      | Individual     | Collateral Weakness | Auto Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 6                             |
      | Non-Individual | Collateral Weakness | Home Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 0                             |
      | Non-Individual | Collateral Weakness | Home Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 1                             |
      | Non-Individual | Collateral Weakness | Home Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 2                             |
      | Non-Individual | Collateral Weakness | Home Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 3                             |
      | Non-Individual | Collateral Weakness | Home Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 4                             |
      | Non-Individual | Collateral Weakness | Home Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 5                             |
      | Non-Individual | Collateral Weakness | Home Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 6                             |
      | Non-Individual | Collateral Weakness | Personal Loan | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 0                             |
      | Non-Individual | Collateral Weakness | Personal Loan | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 1                             |
      | Non-Individual | Collateral Weakness | Personal Loan | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 2                             |
      | Non-Individual | Collateral Weakness | Personal Loan | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 3                             |
      | Non-Individual | Collateral Weakness | Personal Loan | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 4                             |
      | Non-Individual | Collateral Weakness | Personal Loan | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 5                             |
      | Non-Individual | Collateral Weakness | Personal Loan | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 6                             |
      | Non-Individual | Collateral Weakness | Auto Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 0                             |
      | Non-Individual | Collateral Weakness | Auto Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 1                             |
      | Non-Individual | Collateral Weakness | Auto Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 2                             |
      | Non-Individual | Collateral Weakness | Auto Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 3                             |
      | Non-Individual | Collateral Weakness | Auto Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 4                             |
      | Non-Individual | Collateral Weakness | Auto Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 5                             |
      | Non-Individual | Collateral Weakness | Auto Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error |              | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 6                             |

  #FeatureID-ACAUTOCAS-630
  Scenario Outline: ACAUTOCAS-4727: Validating Executive Summary in Decision Justification Details <var> at Recommendation
    Given user is on CAS Login Page
    And user logged in CAS with valid username and password present in "<SourceDataFile>" under "<SheetName>" and 0
    And user logout from CAS
    And user logged in CAS with valid username and password present in "LoginDetailsCAS.xlsx" under "LoginData" and 0
    And user opens an application at "<Var_Stage>" stage from application grid
    And user is on Decision Justification details at recommendation
    And user reads data from the excel file "<RecommendationWB>" under sheet "<Recommendation_default>" and row <Recommendation_default_rowNum>
    When user enters "<FieldName>" "<var>" in Decision Justification Details at recommendation for "<Applicant>" at "<Loan_Type>"
    Then "<FieldName>" field with "<Throws_notThrows>" in Decision Justification Details at recommendation
    Examples:
      | Applicant      | FieldName         | Loan_Type     | var                       | SourceDataFile       | SheetName | Throws_notThrows         | Var_Stage                       | RecommendationWB    | Recommendation_default | Recommendation_default_rowNum |
      | Individual     | Executive Summary | Home Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 0                             |
      | Individual     | Executive Summary | Home Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 1                             |
      | Individual     | Executive Summary | Home Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 2                             |
      | Individual     | Executive Summary | Home Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 3                             |
      | Individual     | Executive Summary | Home Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 4                             |
      | Individual     | Executive Summary | Home Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 5                             |
      | Individual     | Executive Summary | Home Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_individual_hl    | recommendation.xlsx | decision_justification | 6                             |
      | Individual     | Executive Summary | Personal Loan | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation                  | recommendation.xlsx | decision_justification | 0                             |
      | Individual     | Executive Summary | Personal Loan | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation                  | recommendation.xlsx | decision_justification | 1                             |
      | Individual     | Executive Summary | Personal Loan | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation                  | recommendation.xlsx | decision_justification | 2                             |
      | Individual     | Executive Summary | Personal Loan | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation                  | recommendation.xlsx | decision_justification | 3                             |
      | Individual     | Executive Summary | Personal Loan | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation                  | recommendation.xlsx | decision_justification | 4                             |
      | Individual     | Executive Summary | Personal Loan | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation                  | recommendation.xlsx | decision_justification | 5                             |
      | Individual     | Executive Summary | Personal Loan | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation                  | recommendation.xlsx | decision_justification | 6                             |
      | Individual     | Executive Summary | Auto Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 0                             |
      | Individual     | Executive Summary | Auto Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 1                             |
      | Individual     | Executive Summary | Auto Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 2                             |
      | Individual     | Executive Summary | Auto Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 3                             |
      | Individual     | Executive Summary | Auto Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 4                             |
      | Individual     | Executive Summary | Auto Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 5                             |
      | Individual     | Executive Summary | Auto Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_individual_mal    | recommendation.xlsx | decision_justification | 6                             |
      | Non-Individual | Executive Summary | Home Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 0                             |
      | Non-Individual | Executive Summary | Home Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 1                             |
      | Non-Individual | Executive Summary | Home Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 2                             |
      | Non-Individual | Executive Summary | Home Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 3                             |
      | Non-Individual | Executive Summary | Home Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 4                             |
      | Non-Individual | Executive Summary | Home Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 5                             |
      | Non-Individual | Executive Summary | Home Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_nonindividual_hl | recommendation.xlsx | decision_justification | 6                             |
      | Non-Individual | Executive Summary | Personal Loan | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 0                             |
      | Non-Individual | Executive Summary | Personal Loan | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 1                             |
      | Non-Individual | Executive Summary | Personal Loan | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 2                             |
      | Non-Individual | Executive Summary | Personal Loan | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 3                             |
      | Non-Individual | Executive Summary | Personal Loan | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 4                             |
      | Non-Individual | Executive Summary | Personal Loan | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 5                             |
      | Non-Individual | Executive Summary | Personal Loan | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_nonindividual_pl | recommendation.xlsx | decision_justification | 6                             |
      | Non-Individual | Executive Summary | Auto Loan     | valid value               | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 0                             |
      | Non-Individual | Executive Summary | Auto Loan     | with characters           | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 1                             |
      | Non-Individual | Executive Summary | Auto Loan     | with special character    | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 2                             |
      | Non-Individual | Executive Summary | Auto Loan     | with characters and digit | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 3                             |
      | Non-Individual | Executive Summary | Auto Loan     | with spaces               | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 4                             |
      | Non-Individual | Executive Summary | Auto Loan     | negative                  | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 5                             |
      | Non-Individual | Executive Summary | Auto Loan     | hyphen                    | LoginDetailsCAS.xlsx | LoginData | does not throw any error | recommendation_nonindividual_mal | recommendation.xlsx | decision_justification | 6                             |

